### ISSUE TITLE
selenium-webdriver 3.4.1 or above breaks Selenium::WebDriver.for

### ISSUE THREAD

**Issue by kev-in-shu** [SeleniumHQ/selenium#4187]
## Meta -
OS:  
Windows
Selenium Version:  
3.4.2
Browser:  
Chrome

Browser Version:  

## Expected Behavior -
Being able to launch another browser with default capabilities as supported by version 3.4.0, with the [syntax described on the wiki](https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings)

driver = Selenium::WebDriver.for :remote, desired_capabilities: :firefox

or

driver = Selenium::WebDriver.for :remote, desired_capabilities: :chrome

## Actual Behavior -

NoMethodError:
       undefined method `capabilities' for :firefox:Symbol

or

NoMethodError:
       undefined method `capabilities' for :chrome:Symbol

This syntax used to work with version 3.4.0, but it does not work with 3.4.1 or 3.4.2

**Comment by p0deje** [comment]
Thank you for report, it will be fixed today!

**Comment by p0deje** [comment]
This should be fixed in 3.4.3, please give it a shot!

**Comment by p0wl** [comment]
does not seem to be fixed:

```
...
Using selenium-webdriver 3.4.3
Using capybara 2.14.2
...
```


```
NoMethodError:
            undefined method `capabilities' for nil:NilClass
          # /app/.bundle/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/remote/w3c/capabilities.rb:152:in `from_oss'
          # /app/.bundle/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/remote/bridge.rb:183:in `merged_capabilities'
          # /app/.bundle/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/remote/bridge.rb:103:in `create_session'
          # /app/.bundle/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/remote/bridge.rb:54:in `handshake'
          # /app/.bundle/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/remote/driver.rb:33:in `new'
          # /app/.bundle/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/common/driver.rb:58:in `for'
          # /app/.bundle/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver.rb:86:in `for'
          # /app/.bundle/gems/capybara-2.14.3/lib/capybara/selenium/driver.rb:23:in `browser'
          # /app/.bundle/gems/capybara-2.14.3/lib/capybara/selenium/driver.rb:67:in `visit'
          # /app/.bundle/gems/capybara-2.14.3/lib/capybara/session.rb:269:in `visit'
          # /app/.bundle/gems/capybara-2.14.3/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
```

**Comment by p0deje** [comment]
I don't know what are you doing here, but I cannot reproduce:

```irb
irb(main):001:0> require 'selenium-webdriver'
=> true
irb(main):002:0> driver = Selenium::WebDriver.for(:remote, desired_capabilities: :firefox)
=> #<Selenium::WebDriver::Remote::OSS::Driver:0x2d51ecbf9aff8aa2 browser=:firefox>
irb(main):003:0> driver.get 'http://google.com'
=> nil
irb(main):004:0> driver.title
=> "Google"
irb(main):005:0> driver.quit
=> nil
```

If you're passing something different from Symbol to `:desired_capabilities`, please create another issue with [concise reproducible test case](http://sscce.org/).

**Comment by kev-in-shu** [comment]
Works like a charm with version 3.4.3!

Thanks for the fix.

**Comment by SlightlyCyborg** [comment]
This is still broken in the gem repo btw.

**Comment by barancev** [comment]
@SlightlyCyborg Open a new issue and provide a reproduction scenario

**Comment by p0deje** [comment]
@SlightlyCyborg What do you mean that it's broken? https://rubygems.org/gems/selenium-webdriver latest version is 3.5.0 and it contains a fix.

**Comment by SlightlyCyborg** [comment]
I mean it didn't work for me and I received this error. I had just
installed the webdriver gem. I ended up not using this solution for
scraping and I don't have time to replicate it for debugging. Perhaps it is
just an issue with my own system and there is no other problem.

Thanks for helping out and I am sorry I can't follow up on this.
