### ISSUE TITLE
[🐛 Bug]:Open browser doesn't work with Edge + Selenium==4.1.0('Options' object has no attribute 'use_chromium') but OK with Edge + selenium==4.0.0.rc2

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#10184]
### What happened?

Hello, after upgrading Selenium to 4.1.0, when I launch a simple test case RobotFramework on Edge(Version 96.0.1054.62)

I have this error: **'Options' object has no attribute 'use_chromium'** and no browser is open but it works well with selenium==4.0.0.rc2

Is this an evolution ?

**Fail** with packages:
Python 3.9.4, robotframework==4.1.3, robotframework-seleniumlibrary==5.1.3, selenium==4.1.0

**Pass** with packages:
Python 3.9.4, robotframework==4.1.3, robotframework-seleniumlibrary==5.1.3, selenium==4.0.0.rc2

### How can we reproduce the issue?

```shell
SeleniumLibrary.Open Browser   ${url}    edge    options=use_chromium=True
```

### Relevant log output

```shell
FAIL AttributeError: 'Options' object has no attribute 'use_chromium'
```

### Operating System

Windows 10

### Selenium version

selenium==4.1.0

### What are the browser(s) and version(s) where you see this issue?

Edge Version 96.0.1054.62

### What are the browser driver(s) and version(s) where you see this issue?

MSEdgeDriver 96.0.1054.62

**Comment by titusfortner** [comment]
We have removed support for EdgeHTML from Selenium 4, so all references to Edge are for Chromium Edge, so there is no need to have a method to toggle it. Perhaps the Robot library needs to be updated to reflect this?

**Comment by ghost** [comment]
Yes, it's ok without args "options=use_chromium=True" with Selenium==4.1.0.
I found this https://github.com/SeleniumHQ/selenium/pull/9921
Thank's
