### ISSUE TITLE
driver.quit() throws exception in selenium version 2.53.0

### ISSUE THREAD

**Issue by hvardhan89** [SeleniumHQ/selenium#1982]
## Meta -
OS: Window 7 Professional
Selenium Version: Webdriver 2.53.0
Browser: Internet Explorer 
Browser Version: 11.0.9600.1628 (64-bit)

## Steps to reproduce -
when I updated selenium webdriver from 2.43.1 to 2.53.0, I got exception when jvm run the driver.quit() method. Find below the portion of stacktrace.

`Exception in thread "Thread-2" java.lang.NoClassDefFoundError: com/sun/jna/platform/win32/Kernel32
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:133)
	at org.openqa.selenium.os.ProcessUtils.killProcess(ProcessUtils.java:81)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.destroyHarder(UnixProcess.java:247)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$2(UnixProcess.java:246)
	at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:125)
	at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:155)
	at org.openqa.selenium.remote.service.DriverService.stop(DriverService.java:196)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:94)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:701)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:526)`

**Comment by hvardhan89** [comment]
not valid

**Comment by LeonChenTw** [comment]
I have the same problem and found a workaround:
Add the dependency to downgrade jna:
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>platform</artifactId>
    <version>3.5.2</version>
</dependency>


It worked for a simple project, but I am not sure if there is any side effect.

**Comment by marcandregirard** [comment]
@hvardhan89 Why is this not valid ? I have the same problem, but I can't find a solution to it. Did you find anything on it ? I don't want to downgrade the version.
