### ISSUE TITLE
failed to build source code and got error in java\server\src\org\openqa\selenium\remote\se rver\AllHandlers.java:162

### ISSUE THREAD

**Issue by gleechad** [SeleniumHQ/selenium#5879]
## Meta -
OS:  

Windows Server 2012 R2
Selenium Version:  

3.8
Browser:  

n/a

Browser Version:  

n/a

## Expected Behavior -
source code can be built without errors. 
## Actual Behavior -
source code building failed due to the below errors:

## Steps to reproduce -

1. Set JAVA_HOME to jdk1.8
2. Download source code of version 3.8 
3. run go dotnet in selenium source code folder.
observed:
error reported after a while:
C:\selenium-selenium-3.8.0>go dotnet
Downloading buck build tool, it can take up to several minutes...
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:188: warning: singleton on non-persistent Java type Java::OrgApacheHttpConn::HttpHostConnectException (http://wiki.jruby.org/Persistence)
go aborted!
Java::OrgApacheHttpConn::HttpHostConnectException: Connect to github.com:443 [github.com/192.30.255.113, github.com/192.30.255.112] failed: Connection timed out: connect
org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(org/apache/http/impl/conn/DefaultHttpClientConnectionOperator.java:159)
org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(org/apache/http/impl/conn/PoolingHttpClientConnectionManager.java:359)
org.apache.http.impl.execchain.MainClientExec.establishRoute(org/apache/http/impl/execchain/MainClientExec.java:381)

After changing buck.rb by setting HTTP Proxy, run 'go', and the following error is reported in the process of building.

er#class-abi
BUILD FAILED: //java/server/src/org/openqa/selenium/remote/server:webdriver-serv
let failed with exit code 1:
javac_jar
stderr: C:\selenium-selenium-3.8.0\java\server\src\org\openqa\selenium\remote\se
rver\AllHandlers.java:162: error: unreported exception X; must be caught or decl
ared to be thrown
            .orElseThrow(() -> new IllegalArgumentException(
                        ^
C:\selenium-selenium-3.8.0\java\server\src\org\openqa\selenium\remote\server\Act
iveSessionFactory.java:-1: note: C:\selenium-selenium-3.8.0\java\server\src\org\
openqa\selenium\remote\server\ActiveSessionFactory.java uses or overrides a depr
ecated API.

C:\selenium-selenium-3.8.0\java\server\src\org\openqa\selenium\remote\server\Act
iveSessionFactory.java:-1: note: Recompile with -Xlint:deprecation for details.

C:\selenium-selenium-3.8.0\java\server\src\org\openqa\selenium\remote\server\All
Handlers.java:-1: note: Some input files use unchecked or unsafe operations.

C:\selenium-selenium-3.8.0\java\server\src\org\openqa\selenium\remote\server\All
Handlers.java:-1: note: Recompile with -Xlint:unchecked for details.

Errors: 1. Warnings: 0.

BUILT 314/336 JOBS 21.7s //javascript/firefox-driver:driver-component
DOWNLOADED 0.00 BYTES/SEC AVG, 0 ARTIFACTS, 0.00 BYTES
BUILDING: FINISHED IN 3m 29.4s (100%) 314/336 JOBS, 314 UPDATED, 93.2% CACHE MIS
S

**Comment by barancev** [comment]
What version of Java SDK do you use? It looks similar to this bug: https://bugs.openjdk.java.net/browse/JDK-8054569

**Comment by gleechad** [comment]
JDK info:
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

Got another error after upgrade JDK from 1.8.0 to 1.8.0_172.
Kindly please help to take a look at the issue. 

2018-05-14 00:48:27,729 [WARNING][buck_tool.py:398] Not using buckd because watchman isn't installed.
PARSING BUCK FILES... 3.5s (100%)
CREATING ACTION GRAPH: FINISHED IN 0.7s
DOWNLOADED 0 ARTIFACTS, 0.00 BYTES
BUILDING: FINISHED IN 15.7s (100%) 130/131 JOBS, 53 UPDATED, 0.0% CACHE MISS
BUILD SUCCEEDED
TESTING //javascript/atoms:atoms-chrome
FAIL     57.1s 52 Passed   0 Skipped   1 Failed   org.openqa.selenium.javascript.ClosureTestSuite
FAILURE org.openqa.selenium.javascript.ClosureTestSuite : JavaScript errors detected by test runner:
Error: Failed to execute 'createShadowRoot' on 'Element': Shadow root cannot be created on a host which already hosts a
shadow tree.
    at http://localhost:5724/javascript/atoms/test/html5/shadow_dom_test.html:80:62


org.openqa.selenium.javascript.JavaScriptAssertionError: JavaScript errors detected by test runner:
Error: Failed to execute 'createShadowRoot' on 'Element': Shadow root cannot be created on a host which already hosts a
shadow tree.
    at http://localhost:5724/javascript/atoms/test/html5/shadow_dom_test.html:80:62



====STANDARD OUT====

====DEBUG LOGS====

[2018-05-14 00:49:32.135][info ][tid:11][org.openqa.selenium.javascript.ClosureTestStatement] Running: http://localhost:
5724/javascript/atoms/test/html5/shadow_dom_test.html
[2018-05-14 00:49:32.136][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executing: maximizeCurrentWindow [8
4173b9afeee0fff7a759821258203aa, maximizeCurrentWindow {}]
[2018-05-14 00:49:32.139][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executed: [84173b9afeee0fff7a759821
258203aa, maximizeCurrentWindow {}]
[2018-05-14 00:49:32.139][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executing: executeScript [84173b9af
eee0fff7a759821258203aa, executeScript {script=if (window && window.top) window.top.G_testRunner = null, args=[]}]
[2018-05-14 00:49:32.146][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executed: [84173b9afeee0fff7a759821
258203aa, executeScript {script=if (window && window.top) window.top.G_testRunner = null, args=[]}]
[2018-05-14 00:49:32.146][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executing: get [84173b9afeee0fff7a7
59821258203aa, get {url=http://localhost:5724/javascript/atoms/test/html5/shadow_dom_test.html}]
[2018-05-14 00:49:32.165][info ][tid:17][org.seleniumhq.jetty9.server.ResourceService] content=ResourceHttpContent@50da9
286{r=file:///C:/selenium-selenium-3.9.1/javascript/atoms/test/html5/shadow_dom_test.html,ct=text/html,c=false}
[2018-05-14 00:49:32.281][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executed: [84173b9afeee0fff7a759821
258203aa, get {url=http://localhost:5724/javascript/atoms/test/html5/shadow_dom_test.html}]
[2018-05-14 00:49:32.281][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executing: executeScript [84173b9af
eee0fff7a759821258203aa, executeScript {script=var tr = window.top.G_testRunner;return !!tr && tr.isFinished();, args=[]
}]
[2018-05-14 00:49:32.302][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executed: [84173b9afeee0fff7a759821
258203aa, executeScript {script=var tr = window.top.G_testRunner;return !!tr && tr.isFinished();, args=[]}]
[2018-05-14 00:49:32.302][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executing: executeScript [84173b9af
eee0fff7a759821258203aa, executeScript {script=var tr = window.top.G_testRunner;return !!tr && tr.isSuccess();, args=[]}
]
[2018-05-14 00:49:32.309][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executed: [84173b9afeee0fff7a759821
258203aa, executeScript {script=var tr = window.top.G_testRunner;return !!tr && tr.isSuccess();, args=[]}]
[2018-05-14 00:49:32.309][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executing: executeScript [84173b9af
eee0fff7a759821258203aa, executeScript {script=var tr = window.top.G_testRunner;return tr.getReport(true);, args=[]}]
[2018-05-14 00:49:32.319][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executed: [84173b9afeee0fff7a759821
258203aa, executeScript {script=var tr = window.top.G_testRunner;return tr.getReport(true);, args=[]}]

TESTS FAILED: 1 FAILURE
Failed target: //javascript/atoms:atoms-chrome
FAIL org.openqa.selenium.javascript.ClosureTestSuite
go aborted!
python C:/selenium-selenium-3.9.1/buck-out/crazy-fun/8eca783ccd962d873c92c38b5b15b642e3f5e268/buck.pex test --stamp-buil
d=detect //javascript/atoms:atoms-chrome failed with exit code: 32
C:/selenium-selenium-3.9.1/rake-tasks/buck.rb:91:in `block in buck_cmd'
C:/selenium-selenium-3.9.1/rake-tasks/buck.rb:75:in `buck_cmd'
C:/selenium-selenium-3.9.1/rake-tasks/buck.rb:168:in `block in (root)'
C:/selenium-selenium-3.9.1/rake-tasks/buck.rb:94:in `buck_cmd'
C:/selenium-selenium-3.9.1/rake-tasks/buck.rb:164:in `block in (root)'
Tasks: TOP => default => test => test_javascript => //javascript/atoms:atoms-chrome:run
(See full trace by running task with --trace)

**Comment by barancev** [comment]
Please don't mix different isues in the same report.

**Comment by barancev** [comment]
1) Many bugs were fixed since version 3.9, there is no sence to tell us about failed tests in outdated versions.
2) Yes, there might be test failures still, some tests don't pass in some browsers, it's not a bug to be reported here. You welcome to IRC to talk about current development state.
