### ISSUE TITLE
driver.manage.logs.get(:browser) fails on chromedriver 75.0.3770.8

### ISSUE THREAD

**Issue by ShockwaveNN** [SeleniumHQ/selenium#7270]
## 🐛 Bug Report

While accessing `driver.manage.logs.get(:browser)` on chromedriver 75.0.3770.8 - it cause error
```
undefined method `log' for #<Selenium::WebDriver::Remote::W3C::Bridge:0x0000562dc661c250> (NoMethodError)
```
Works fine on 74.0.3729.6

## To Reproduce

Just run test script

## Test script or set of commands reproducing this issue

```
require 'selenium-webdriver'
driver = Selenium::WebDriver.for(:chrome, driver_path: '/tmp/chromedriver_74.0.3729.6')
puts driver.manage.logs.get(:browser)
driver = Selenium::WebDriver.for(:chrome, driver_path: '/tmp/chromedriver_75.0.3770.8')
puts driver.manage.logs.get(:browser)
```
will cause
```
/home/user/.rvm/gems/ruby-2.5.3/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/common/logs.rb:32:in `get': undefined method `log' for #<Selenium::WebDriver::Remote::W3C::Bridge:0x0000562dc661c250> (NoMethodError)
```
on last line, 74 works fine

## Environment

OS: Ubuntu 18.04
Browser: Chrome
Browser version: `75.0.3770.80 `
Browser Driver version: chromedriver 75.0.3770.8
Language Bindings version: `Ruby 'selenium-webdriver', '3.142.3'`

**Comment by ShockwaveNN** [comment]
On changes of chromedriver I din't find any relative info
https://chromedriver.storage.googleapis.com/75.0.3770.8/notes.txt

**Comment by twalpole** [comment]
Chrome 75 defaults to W3C mode which doesn't specify a way to get log access. For now you can disable w3c mode in your driver registration.

**Comment by StefanWallin** [comment]
Thank you for the response @twalpole! 💐 

Do you maybe know how to disable w3c-mode in chrome? I've been perusing the startup arguments for Chrome for quite a while without finding something relevant. Would probably be helpful for future developers searching and stumbling upon this thread as well. 🔍 🙇

**Comment by jimevans** [comment]
As part of the `goog:chromeOptions` capabilities, you need to add a `w3c` property with the value set to `false`. For Ruby, there is likely a `ChromeOptions` class which should let you set this property, but someone more familiar with Ruby would be better able to answer that. However, you should probably start weaning yourself off of calls to non-spec-compliant commands like the logging commands.

**Comment by 6temes** [comment]
Did anyone find the way to deactivate the `w3c` mode though `ChromeOptions`.

**Comment by ShockwaveNN** [comment]
For my example (without Capybara) fixed variant will be
```
require 'selenium-webdriver'
caps = Selenium::WebDriver::Remote::Capabilities.chrome
caps['chromeOptions'] = {
    w3c: false
}
driver = Selenium::WebDriver.for(:chrome, driver_path: '/tmp/chromedriver_75.0.3770.8', desired_capabilities: caps)
puts driver.manage.logs.get(:browser)
```

**Comment by jkotests** [comment]
Are there plans to make the functionality available again?

I haven't had much time to test it, but the following monkey-patch seems to restore the behaviour:

~~~~~~~~ruby
require 'selenium-webdriver'

module Selenium
  module WebDriver
    module Chrome
      module Bridge
        COMMANDS = remove_const(:COMMANDS).dup
        COMMANDS[:get_log] = [:post, 'session/:session_id/log']
        COMMANDS.freeze
        
        def log(type)
          data = execute :get_log, {}, {type: type.to_s}

          Array(data).map do |l|
            begin
              LogEntry.new l.fetch('level', 'UNKNOWN'), l.fetch('timestamp'), l.fetch('message')
            rescue KeyError
              next
            end
          end
        end
      end
    end
  end
end
  
# Note that you need to switch the capability to "goog:loggingPrefs" (previously "loggingPrefs")
caps = Selenium::WebDriver::Remote::Capabilities.chrome('goog:loggingPrefs' => {browser: 'ALL'})
driver = Selenium::WebDriver.for(:chrome, desired_capabilities: caps)

driver.execute_script('console.log("test");')

puts driver.manage.logs.get(:browser)
#=> INFO 2019-06-13 21:48:03 -0400: console-api 362:34 "test"
~~~~~~~~
