### ISSUE TITLE
Network throttling not working in Selenium Grid 3.13

### ISSUE THREAD

**Issue by ay0o** [SeleniumHQ/selenium#6226]
Selenium Grid 3.13 with Chrome nodes. Created using selenium/hub:3.13 and selenium/node-chrome:3.13 Docker images.

According to the [changelog](https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG), since 3.13 it's possible to use `get_network_conditions()` and `set_network_conditions()` to simulate lower speeds.

However, assume the following Python snippet:

```
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

driver = webdriver.Remote(
    command_executor='http://selenium:4444/wd/hub',
    desired_capabilities=getattr(DesiredCapabilities, "CHROME")
)
print(driver.get_network_conditions())
driver.close()
```

It's reporting:

`AttributeError: 'WebDriver' object has no attribute 'get_network_conditions'`

**Comment by lmtierney** [comment]
Duplicate of #6217
