### ISSUE TITLE
java.lang.NoClassDefFoundError: org/openqa/selenium/net/PortProber -- After updating to version 4.0.0-alpha-3

### ISSUE THREAD

**Issue by Naumansh** [SeleniumHQ/selenium#7695]
## 🐛 Bug Report

**iSSUE**
Updated to selenium version 4.0.0-alpha-3 and selenium server version 4.0.0-alpha-2 from Selenium 3.14.59.
Everything works fine with 3.14.59 but right after updating to new version below exception is comming up on all browsers:
**java.lang.NoClassDefFoundError: org/openqa/selenium/net/PortProber
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.net.PortProber**

**Full Stack Trace**
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:26)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:20)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:65)
	at cucumber.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:16)
	at cucumber.runner.TestStep.executeStep(TestStep.java:65)
	at cucumber.runner.TestStep.run(TestStep.java:50)
	at cucumber.runner.TestCase.run(TestCase.java:50)
	at cucumber.runner.Runner.runPickle(Runner.java:50)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:146)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:330)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:78)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:328)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:65)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:292)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:305)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:412)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:142)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:65)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:330)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:78)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:328)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:65)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:292)
	at io.cucumber.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:172)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:305)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:412)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

**Options and service used for chrome**
ChromeDriverService chromeService = new ChromeDriverService.Builder().usingAnyFreePort().usingAnyFreePort().build();

        ChromeOptions chromeOptions = new ChromeOptions();
        HashMap<String, Object> chromePrefs = new HashMap<>();
        chromePrefs.put("profile.default_content_settings.popups", 0);
        chromePrefs.put("download.prompt_for_download", "false");
        chromePrefs.put("download.directory_upgrade", "true");
        chromePrefs.put("download.default_directory", System.getProperty("user.dir") + File.separator + "target");
        chromeOptions.setExperimentalOption("prefs", chromePrefs);
        chromeOptions.addArguments("--window-size=1920,1080");
        chromeOptions.setUnhandledPromptBehaviour(UnexpectedAlertBehaviour.IGNORE);
this.driver = new ChromeDriver(chromeOptions);

**To Reproduce**
Chrome version : 77
OS: Any
Selenium version 4.0.0-alpha-3

It also appears that may be services is not a mandatory requirement to pass to chromeDriver constructor. However same exception is thrown with and without services.

**Comment by barancev** [comment]
Please show your classpath

**Comment by barancev** [comment]
Closing due to inactivity
