### ISSUE TITLE
Failing Atom bazel build

### ISSUE THREAD

**Issue by Harsha509** [SeleniumHQ/selenium#8147]
## 💥 Regression Report

atom bazel build is failing with changes in pr #8102

## To Reproduce

bazel build javascript/...

## Error:

ERROR: /Users/sriharsha/Desktop/selenium/javascript/webdriver/atoms/BUILD.bazel:42:1: Compiling 710 JavaScript files to javascript/webdriver/atoms/clear-local-storage-ios.js failed (Exit 1)
javascript/webdriver/atoms/storage/local_storage.js:55: ERROR - The return type of the function "webdriver.atoms.storage.local.keySet" is nullable, but it always returns a non-null value. Consider making the return type non-nullable.
webdriver.atoms.storage.local.keySet = function() {
                                       ^
  ProTip: "JSC_NULLABLE_RETURN_WITH_NAME" or "analyzerChecks" or "analyzerChecksInternal" can be added to the `suppress` attribute of:
  //javascript/webdriver/atoms:atoms-lib

1 error(s), 0 warning(s), 97.7% typed

INFO: Elapsed time: 332.019s, Critical Path: 136.91s
INFO: 1545 processes: 6 remote cache hit, 364 darwin-sandbox, 1175 worker.
FAILED: Build did NOT complete successfully

## Environment

OS: MacOs 10.15.4
Bazel Version: 2.2.0

**Comment by Harsha509** [comment]
HI @AutomatedTester ,

Build is passing after reverting change in this file `javascript/atoms/html5/storage.js` 

Regards,
Harsha
