### ISSUE TITLE
Python Selenium 3.3.0 breaks with remote_connection.py:480: AttributeError

### ISSUE THREAD

**Issue by martinpelikan** [SeleniumHQ/selenium#3692]
## Meta -
Language:
Python
Python Version:
3.4.6
OS:  
Linux
Selenium Version:  
3.3.1
Browser:  
Remote Driver w/ Chrome via Sauce Labs
Browser Version:  
56.0.2924.76

## Expected Behavior -
Don't try to decode a string.

## Actual Behavior -
```Python
/tmp/tox/webui/lib/python3.4/site-packages/webium/base_page.py:63: in open
    self._driver.get(self.url)
/tmp/tox/webui/lib/python3.4/site-packages/webium/base_page.py:52: in _driver
    return get_driver()
/tmp/tox/webui/lib/python3.4/site-packages/webium/driver.py:10: in get_driver
    _driver_instance = webium.settings.driver_class()
/tmp/tox/webui/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py:92: in __init__
    self.start_session(desired_capabilities, browser_profile)
/tmp/tox/webui/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py:179: in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
/tmp/tox/webui/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py:236: in execute
    response = self.command_executor.execute(driver_command, params)
/tmp/tox/webui/lib/python3.4/site-packages/selenium/webdriver/remote/remote_connection.py:415: in execute
    return self._request(command_info[0], url, body=data)
...
            if parsed_url.username:
                base64string = base64.b64encode('{0.username}:{0.password}'.format(parsed_url).encode())
>               request.add_header('Authorization', 'Basic {}'.format(base64string).decode())
E               AttributeError: 'str' object has no attribute 'decode'

/tmp/tox/webui/lib/python3.4/site-packages/selenium/webdriver/remote/remote_connection.py:480: AttributeError
```

This issue appears to be introduced by #3622 / 55ed929d64e96c518c89244dd4a6fccc85865fc0, which itself was addressing another string/bytes related issue.

The return of `.format()` is a string, which you have no need to further decode.

Demonstration via the debugger:

```Python
ipdb> type(base64string)
<class 'bytes'>
ipdb> type('Basic {}'.format(base64string))
<class 'str'>

ipdb> hasattr(base64string, 'decode')
True
ipdb> hasattr('Basic {}'.format(base64string), 'decode')
False
```

## Steps to reproduce -
This is probably going to be a problem with every Python3 version (confirmed on 3.4 and 3.6), you can do as follows:
```Python
In [1]: from selenium.webdriver.remote import remote_connection
In [2]: rc = remote_connection.RemoteConnection('http://user:123-key@123.45.67.89:80/wd/hub/session')
In [3]: rc._request('POST', 'http://user:123-key@123.45.67.89:80/wd/hub/session', '{}')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-32515677cc7a> in <module>()
----> 1 rc._request('POST', 'http://user:123-key@123.45.67.89:80/wd/hub/session', '{}')

/usr/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py in _request(self, method, url, body)
    478             if parsed_url.username:
    479                 base64string = base64.b64encode('{0.username}:{0.password}'.format(parsed_url).encode())
--> 480                 request.add_header('Authorization', 'Basic {}'.format(base64string).decode())
    481 
    482             if password_manager:

AttributeError: 'str' object has no attribute 'decode'
```

## Fix -
- Remove the unnecessary `.decode()` call

**Comment by lmtierney** [comment]
This was fixed with https://github.com/SeleniumHQ/selenium/commit/7d1286e7fccb82bd354591163399e6bdb1b18088 and will be in the next release
