### ISSUE TITLE
[🐛 Bug]: fail  SeleniumManager.driver_location("chrome") and driver.get(URLx)

### ISSUE THREAD

**Issue by balloumn** [SeleniumHQ/selenium#11514]
### What happened?

fail to get SeleniumManager.driver_location("chrome") and driver.get(URLx)

### How can we reproduce the issue?

```shell
code used:

from selenium import webdriver
from selenium.webdriver.common.selenium_manager import SeleniumManager

os.environ["HTTP_PROXY"] = "http://login:password@appgw.gnb.st.com:8080"
os.environ["HTTPS_PROXY"] = "http://login:password@appgw.gnb.st.com:8080"

time.sleep(2)
print(".......")
os.environ["HTTP_PROXY"] = ""
os.environ["HTTPS_PROXY"] = ""
print("Proxy UnSettings Done")

path2 = SeleniumManager.driver_location("chrome")
driver = webdriver.Chrome(executable_path=path2)
driver.get(URLx)

it work with selenium 4.6.0 but the same code failed with 4.7.1
```

### Relevant log output

```shell
C:\Users\balloumn\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'appgw.gnb.st.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\balloumn\NotSync\Myscript\project_IDT05\test2.py", line 34, in <module>
    path2 = SeleniumManager.driver_location("chrome")
TypeError: SeleniumManager.driver_location() missing 1 required positional argument: 'browser'
```

### Operating System

Win 11

### Selenium version

4.7.1

### What are the browser(s) and version(s) where you see this issue?

108.0.5359.125

### What are the browser driver(s) and version(s) where you see this issue?

108.0.5359.71

### Are you using Selenium Grid?

NO

**Comment by titusfortner** [comment]
Do not use SeleniumManager directly. If Selenium does not find a driver on your system, it will use Selenium Manager in the background for you.

**Comment by balloumn** [comment]
can you suggest a simple code with selenium 4.7.1 please :)

**Comment by titusfortner** [comment]
https://www.selenium.dev/documentation/webdriver/getting_started/first_script/?language=python#putting-everything-together

**Comment by balloumn** [comment]
from selenium import webdriver
from selenium.webdriver.common.by import By


def test_eight_components():
    driver = webdriver.Chrome()

    driver.get("https://www.selenium.dev/selenium/web/web-form.html")

    title = driver.title
    assert title == "Web form"

    driver.implicitly_wait(0.5)

    text_box = driver.find_element(by=By.NAME, value="my-text")
    submit_button = driver.find_element(by=By.CSS_SELECTOR, value="button")

    text_box.send_keys("Selenium")
    submit_button.click()

    message = driver.find_element(by=By.ID, value="message")
    value = message.text
    assert value == "Received!"

    driver.quit()


test_eight_components()




Result :
--------

Traceback (most recent call last):
  File "C:\Users\balloumn\NotSync\Myscript\project_IDT05\test3.py", line 28, in <module>
    test_eight_components()
  File "C:\Users\balloumn\NotSync\Myscript\project_IDT05\test3.py", line 6, in test_eight_components
    driver = webdriver.Chrome()
  File "C:\Users\balloumn\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    super().__init__(
  File "C:\Users\balloumn\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 103, in __init__
    self.service.start()
  File "C:\Users\balloumn\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 100, in start
    raise err
  File "C:\Users\balloumn\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 90, in start
    self._start_process(self.path)
  File "C:\Users\balloumn\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 213, in _start_process
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

**Comment by titusfortner** [comment]
Can you run with a logger turned on?
Something like this should work I think:
```
    selenium_logger = logging.getLogger("selenium")
    selenium_logger.setLevel(10)
    handler = logging.StreamHandler(sys.stdout)
    selenium_logger.addHandler(handler)
```
