### ISSUE TITLE
FluentWait changes WebDriverWait().until(ExpectedCondition...) fails with java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by NikolayStanoev** [SeleniumHQ/selenium#3606]
## Meta
OS:  Windows 7
Selenium Version:  3.2.0
Browser:  Chrome (problem is not related to browser)
Browser Version:  56.0.2924.87 (64-bit)
Java: jdk 1.8 (latest)

## Problem
I had the following setup:
OS:  Windows 7
Selenium Version:  3.0.1
Browser:  Chrome (problem is not related to browser)
Browser Version:  56.0.2924.87 (64-bit)
Java: jdk 1.8 (latest)

I was using guava - 18.0 version and had a tests which were running fine. 

Then I decided to upgrade the whole selenium grid environment to use 3.2.0 webdriver. I went through the changes and updated the pom.xml file to use 3.2.0 selenium-java and guava 21.0.
Then I ran the same tests and all of them failed in the following code fragment:

```
public void waitForElementToLoad(By locator, long timeOutInSeconds) {
        new WebDriverWait(webDriver, timeOutInSeconds).until(ExpectedConditions.visibilityOfElementLocated(locator));
    }
```

with the following reason:
```
 java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.WebDriverWait.until(Ljava/util/function/Function;)Ljava/lang/Object;
```

## Expected Behavior 
If the error above is expected please add some suggestions how to use WebDriverWait + ExpectedConditions

## Actual Behavior 
The tests are failing because of the changes done related to FluentWait. Same piece of code works fine with 3.0.1 and guava 18.0.

## Steps to reproduce 
```
    @Test
    public void example() throws Throwable {
        webDriver.get("https://www.google.com/");
        new WebDriverWait(webDriver, 30000).until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[name='q']")));
    }
```

Thank you in advance!

**Comment by diemol** [comment]
I was checking the change log for 3.2.0 [here](https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG), and it says:
* Remove deprecated `FluentWait.until(Predicate<?>)` method. This
  should make lambdas work properly with Wait instances now.

I think this is related to your error.

**Comment by smathistad** [comment]
@diemol  Actually, this issue does not appear to be related to the deprecated `FluentWait.until(Predicate<?>)` method. 

The issue deals with the parameter `ExpectedConditions.visibilityOfElementLocated()` being used in the `FluentWait.until()` method.   `ExpectedConditions.visibilityOfElementLocated()` is an `org.openqa.selenium.support.ui.ExpectedCondition` which extends the `com.google.common.base.Function` class and that extends the `java.util.function.Function` class.

The method is looking for a `java.util.function.Function` parameter, so a parameter of type `org.openqa.selenium.support.ui.ExpectedCondition` should work.  Why does it fail using guava-18.jar and then work after upgrading to guava-21.jar?

**Comment by smathistad** [comment]
Actually, I just read the [selenium/java/CHANGELOG](https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG#L18-L19) for version 3.2.0.  They upgraded to guava-21.jar

**Comment by diemol** [comment]
You are completely right @smathistad, the Guava upgrade is the reason. Somehow I overlooked that part.

**Comment by MichaelCowanPdx** [comment]
Uhhh. So what is the resolution?

I have a Java Maven project and all I have for selenium in pom is 
<dependency>
                <groupId>org.seleniumhq.selenium</groupId>
                <artifactId>selenium-java</artifactId>
                <version>3.3.1</version>
            </dependency>

I get this error now (but not for 2.53) how do I resolve it?

**Comment by bennid** [comment]
This breaks findBy annotations / PageFactory.initElements as well... any update on this?

**Comment by chernyak-andrew** [comment]
Hi,
If you use maven - execute 'mvn dependency:tree -Dverbose' - verbose flag display conflicting dependencies
Make search by results of dependency tree and find "guava" - if there few libs "guava" in different dependencies with conflicts - make exclude for older versions of guava in another dependencies and leave v.21.0 
This problem may be related to so called Maven "nearest-wins" strategy during resolving version conflicts of transitive dependencies.
Best way - use maven "dependencyManagemenet" 
<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>21.0</version>
      </dependency>
   </dependencies>
</dependencyManagement>

In this way maven always resolve conflict with version from dependencyManagement

**Comment by shabana-parveen** [comment]
Yes, I am also getting the same issue with guava version as Latest, My issue get resolved when I mentioned the guava version as 21 in dependency.

**Comment by JiaYangSF** [comment]
I have guava 21.0 added to my pom.xml, running mvn -f pom.xml compile test, the test passed, wait.until is working fine!
However, if I run it through testng.xml, it will throw this error:
java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.WebDriverWait.until(Ljava/util/function/Function;)Ljava/lang/Object;
	at com.myfico.selenium.testcases.common.CommonTestUtils.waitforElementToPresentById(CommonTestUtils.java:80)
	at com.myfico.selenium.testcases.purchasePath.CommonUtilPurchasePath.testPurchaseProduct(CommonUtilPurchasePath.java:44)
	at com.myfico.selenium.testcases.purchasePath.testPlaceOrderWithPromoCodeScenarioAllProducts.testPurchaseFlowHappyPath_Prod20001(testPlaceOrderWithPromoCodeScenarioAllProducts.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)

Setup:
OS: Mac
Selenium Version: 3.4.0
Browser: Chrome (problem is not related to browser)
Java: jdk 1.8 (latest)

POM.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.myfico</groupId>
	<artifactId>WebQA</artifactId>
	<version>1.0</version>
	<properties>
		<jackson2.version>2.3.0</jackson2.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-support</artifactId>
			<version>3.4.0</version>
		</dependency>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-firefox-driver</artifactId>
			<version>3.4.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.13</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.13</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.4.0</version>
		</dependency>
		
		<dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>javax.json</artifactId>
			<version>1.0.4</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.8.21</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.3.2</version>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson2.version}</version>
		</dependency>

		<dependency>
			<groupId>com.jayway.restassured</groupId>
			<artifactId>rest-assured</artifactId>
			<version>2.9.0</version>
		</dependency>
		<dependency>
			<groupId>com.jayway.restassured</groupId>
			<artifactId>json-path</artifactId>
			<version>2.9.0</version>
		</dependency>


	</dependencies>
	<build>
		<finalName>myFICO-WebQA</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.0</version>
				<configuration>
					<source>${jdk.version}</source>
					<target>${jdk.version}</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.20</version>
				
			</plugin>
		</plugins>
	</build>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.opera</groupId>
				<artifactId>operadriver</artifactId>
				<version>1.5</version>
				<exclusions>
					<exclusion>
						<groupId>org.seleniumhq.selenium</groupId>
						<artifactId>selenium-remote-driver</artifactId>
					</exclusion>
				</exclusions>
			</dependency>


			<dependency>
				<groupId>com.google.guava</groupId>
				<artifactId>guava</artifactId>
				<version>21.0</version>
			</dependency>

		</dependencies>
	</dependencyManagement>
</project>

**Comment by garyjing** [comment]
Have the same problem. Got the same error when running via testng.xml. Also cannot run via Eclipse, got the same error as well. 

My settings:
OS: Win 7
Guava 21.0
Selenium Version: 3.4.0
Browser: Chrome (problem is not related to browser)
Java: jdk 1.8 (latest)
Eclipse: Kepler

**Comment by jwmillerX** [comment]
Have the same problem. Got the same error when running via testng.xml. Also cannot run via Eclipse -
 Neon got the same error as well.

My settings:
OS: Win 7
Guava 22.0
Selenium Version: 3.4
Browser: Chrome (problem is not related to browser)
Java: jdk 1.8 (latest)
Eclipse: Neon

**Comment by ivnl** [comment]
This issue happened to me when I added a new dependency to my pom file and re-arranging the new dependency to a lower order in the list seemed to have fixed the issue ..

**Comment by MeghaRamprasad** [comment]
Using guava version 21, still facing this issue. Any solution found for this? Please help.

**Comment by leiwang008** [comment]
The same problem hits me!
I am using:
Java: 1.8.0_144
selenium-server-standalone-3.4.0.jar

-- test code ----------------------------
WebDriverWait wait = new WebDriverWait(webdriver, timeout);
wait.until(ExpectedConditions.alertIsPresent());//NoSuchMethodError is thrown
-----------------------------------------------

When looking inside selenium-server-standalone-3.4.0.jar, I can see
ExpectedConditions.alertIsPresent() returns a ExpectedCondition, which is a subclass of com.google.common.base.Function
com.google.common.base.Function is subclass of java.util.function.Function
WebDriverWait's super class is FluentWait which DOES have a method until(java.util.function.Function)

So WebDriverWait.until(ExpectedConditions.alertIsPresent()) should work, but why it throws 
java.lang.NoSuchMethodError, org.openqa.selenium.support.ui.WebDriverWait.until(Lcom/google/common/base/Function;)Ljava/lang/Object;

**Comment by garyjing** [comment]
Here is my workaround:
1. Open new jar, like 3.5.0, with zip. Delete following classes under \org\openqa\selenium\support\ui:
	FluentWait.class
	Wait.class
	WebDriverWait.class
2. Open jar 3.0.4 or below with zip. Move following classes under \org\openqa\selenium\support\ui:
	FluentWait$1.class
	FluentWait$2.class
	FluentWait$3.class
	FluentWait.class
	Wait.class
	WebDriverWait.class
to the new jar.
Not perfect, but it worked to me.

**Comment by kishoricoep** [comment]
@ivnl , Could you please post you maven pom file. I am trying to update with guava dependency 21 version with selenium 3.9.1 but issue is still there.
Waits are working when executed with eclipse. But failed when executed with testNG.
below error occurred.

java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.WebDriverWait.until(Ljava/util/function/Function;)Ljava/lang/Object;
        at com.pqbook.framework.utils.WaitTool.waitForElementPresent(WaitTool.java:42)
        at com.pqbook.framework.core.BaseElement.getElementByXpath(BaseElement.java:57)
        at com.pqbook.framework.common.TopBar.logoutUser(TopBar.java:45)
        at com.pqbook.framework.core.BaseTestCase.oasisLogout(BaseTestCase.java:251)
        at com.pqbook.framework.core.BaseTestCase.tearDown(BaseTestCase.java:338)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
        at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
        at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:220)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
        at org.testng.TestRunner.privateRun(TestRunner.java:774)
        at org.testng.TestRunner.run(TestRunner.java:624)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
        at org.testng.SuiteRunner.run(SuiteRunner.java:261)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
        at org.testng.TestNG.run(TestNG.java:1048)
        at org.testng.TestNG.privateMain(TestNG.java:1355)
        at org.testng.TestNG.main(TestNG.java:1324)

**Comment by sjethvani** [comment]
I updated below lines in my gradle file and it resolved above NosuchErrorMethod compilation error for 'webdriverwait.until() method'
```
	compile(group: 'com.google.guava', name: 'guava', version: '24.0-jre')
	compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '3.10.0'
```

PS : Guava core has been bifurcated under two libraries (1 jre , 2 android)

**Comment by srivishal** [comment]
Any one get this working with selenium 3.10.0 and guava 21

**Comment by mirza-ae** [comment]
I am also facing this issue. I dont quite understand why this issue was closed when it is clearly a common occurrence. 

Can someone from the Selenium team please re-open this issue?

**Comment by barancev** [comment]
@mirza-ae Yes, misconfiguring classpath is a common occurrence, but it's not a bug that can be fixed in Selenium code, you should fix dependencies in your project.

**Comment by shankar86kd** [comment]
I am using Selenium 3.13.0 jars and with guava 26.0-jre.jar. 
We don't use maven or gradle. We have jars physically added to the eclipse build path and we refer to the jar location in the classpath to execute the automation jar in runtime as below:
java -cp <ProdName>.jar;C:\Selenium\lib/*.jar src.main.Main

I see the following exception whenever I am trying to use WebDriverWait.until(ExpectedConditions):
 java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.FluentWait.until(Lcom/google/common/base/Function;)Ljava/lang/Object;

Sample Code which is hitting issue:

public static void clickSearch(WebDriver driver,By by, int timeout){
		driver.manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);
		WebDriverWait wait = new WebDriverWait(driver, 2);
		WebElement webElement = wait.until(ExpectedConditions.elementToBeClickable(by));

		driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		//return webElement; 
		webElement.click();
	}

Java JDK : 1.8.0_131-b11

**Comment by BalurQA** [comment]
Even I have faced the same issue adding guva and selenium-support dependencies resolved my issue.
<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>21.0</version>
</dependency>


<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-support</artifactId>
    <version>3.2.0</version>
</dependency>


if you are still facing the issue then update selenium standalone server to the selenium version that you are using. there is no maven dependency for selenium standalone server so you have to download the required version and add it to build path.

Note : After adding all above dependencies, delete selenium folder from .m2 folder and build it.

All the best.

**Comment by shankar86kd** [comment]
As mentioned already in my previous comment, I have got latest guava 26.0-jre.jar and following selenium jars : selenium-api-3.13.0.jar, selenium-java-3.13.0.jar, selenium-remote-driver-3.13.0.jar, selenium-server-standalone-3.13.0.jar, selenium-support-3.13.0.jar, client-combined-3.13.0.jar.

Even though I have the above mentioned jars I am seeing this issue. I have many other jars in classpath too. Not sure if any of them is causing the issue.

**Comment by BalurQA** [comment]
@shankar86kd : In your list you do not have selenium support dependency added.  As mentioned in my comment, add this dependency and delete selenium from .m2 folder in your location system and rebuild the project again. It should work.


<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-support</artifactId>
    <version>3.13.0</version>
</dependency>

**Comment by shankar86kd** [comment]
@BalurQA I have selenium-support-3.13.0.jar. And I am not using maven or gradle. We are manually adding the jars in our library. Any help would be appreciated. Thanks !

**Comment by BalurQA** [comment]
@shankar86kd : i tried with little lower versions with Java project by adding below jars then it worked for me.


![image](https://user-images.githubusercontent.com/32229011/44346617-6734d280-a464-11e8-896b-81e314ba030d.png)

**Comment by shankar86kd** [comment]
@BalurQA Yes it was working fine for me when I was on 3.4.0 version. I am trying to upgrade now to latest selenium version as the old version doesnt support latest FF and IE drivers. Hence blocked with this issue.

**Comment by BalurQA** [comment]
@shankar86kd : Try deleting/removing the  selenium-java-3.13.0.jar from library path since you already have selenium-server-standalone-3.13.0.jar. I hope it will work. When I tried with 3.14 version it did work for me.

![image](https://user-images.githubusercontent.com/32229011/44362182-39fd1a00-a48e-11e8-9a84-8b26cf811c48.png)

**Comment by rohitv-iprogrammer** [comment]
Updated the guava jar to 23.0 the issue is resolved

**Comment by EddieEldridge** [comment]
> Here is my workaround:
> 
> 1. Open new jar, like 3.5.0, with zip. Delete following classes under \org\openqa\selenium\support\ui:
>    FluentWait.class
>    Wait.class
>    WebDriverWait.class
> 2. Open jar 3.0.4 or below with zip. Move following classes under \org\openqa\selenium\support\ui:
>    FluentWait$1.class
>    FluentWait$2.class
>    FluentWait$3.class
>    FluentWait.class
>    Wait.class
>    WebDriverWait.class
>    to the new jar.
>    Not perfect, but it worked to me.

After trying to solve this issue for the past 2 days I tried your solution as I wasn't using Maven or any other dependency manager and the jar files were specified with the -cp (classpath) command so the other answers weren't relevant. Thank you very much, it's working perfectly now as i'm able to test on the newer Firefox version without having to refactor large amounts of code either.

**Comment by Praveenroy05** [comment]
Getting similar issue even after trying all the combinations mentioned in the comments.
java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.WebDriverWait.until(Ljava/util/function/Function;)Ljava/lang/Object;

**Comment by idontusenumbers** [comment]
> @mirza-ae Yes, misconfiguring classpath is a common occurrence, but it's not a bug that can be fixed in Selenium code, you should fix dependencies in your project.

In this specific instance, `FluentWait.until()` takes a `java.util.function.Function` but `ExpectedConditions.stalenessOf` returns a `com.google.common.base.Function`, even though both `FluentWait` and `ExpectedConditions` are from the same selenium jar.

https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/support/ui/FluentWait.java#L36
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/support/ui/ExpectedCondition.java#L20

**Comment by barancev** [comment]
@idontusenumbers `com.google.common.base.Function` extends `java.util.function.Function` since guava version 21, see [1]

[1] https://github.com/google/guava/wiki/Release21#commonbase

**Comment by idontusenumbers** [comment]
I dug a little deeper and found the latest https://github.com/docker-java/docker-java still uses guava 19.

Probably still worth replacing the references in the Selenium code base to use the standard library.

**Comment by barancev** [comment]
@idontusenumbers The proposed change would hurt our users that have custom conditions returning a `com.google.common.base.Function`

**Comment by idontusenumbers** [comment]
@barancev it could be done in 4.0; the fix to the user code is easy.
