### ISSUE TITLE
Java zip distribution includes an incompatible htlmunit-driver with bundled htlmunit

### ISSUE THREAD

**Issue by lucasvc** [SeleniumHQ/selenium#4263]
With [version 2.53 you decided to not redistribute `htmlunit-driver`](https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG).
When updating to 3.4.0 I've realized there is again a [`htmlunit-driver.jar` bundled with the .zip distribution](http://selenium-release.storage.googleapis.com/3.4/selenium-java-3.4.0.zip), with a `htmlunit-2.26.jar` dependency included. I though I could use it, but when executing any test using `HtmlUnitDriver` I got:
```
java.lang.NoClassDefFoundError: com/gargoylesoftware/htmlunit/InteractivePage
    at org.openqa.selenium.htmlunit.HtmlUnitDriver$HtmlUnitTargetLocator.activeElement(HtmlUnitDriver.java:1335)
    at org.openqa.selenium.htmlunit.HtmlUnitWebElement.switchFocusToThisIfNeeded(HtmlUnitWebElement.java:292)
    at org.openqa.selenium.htmlunit.HtmlUnitWebElement.sendKeys(HtmlUnitWebElement.java:319)
    at org.openqa.selenium.htmlunit.HtmlUnitWebElement.sendKeys(HtmlUnitWebElement.java:311)
....
```

Which there is no such class in `htmlunit-2.26.jar`. My surprise is that `htmlunit-driver.jar`'s pom file indicates that depends on... 2.23 version, not 2.26 as it is bundled.

**Comment by lucasvc** [comment]
The distribution is ok, is our internal distribution which took a bad version. Sorry for opening the issue >.<
