### PR TITLE
Ensure Firefox capabilities are proper instance by default

### PR DESCRIPTION
**Pull request by p0deje**
This fixes a regression introduced with https://github.com/SeleniumHQ/selenium/commit/00801a07 when default capabilities is an instance of `Hash`, while it should be `Remote::Capabilities`.

Fixes currently failing spec:

```
  1) Selenium::WebDriver::Firefox::Bridge sets the proxy capability
     Failure/Error: Bridge.new(:http_client => http, :proxy => proxy)
     NoMethodError:
       undefined method `proxy=' for {}:Hash
     # ./build/rb/lib/selenium/webdriver/firefox/bridge.rb:41:in `initialize'
     # ./rb/spec/unit/selenium/webdriver/firefox/bridge_spec.rb:41:in `new'
     # ./rb/spec/unit/selenium/webdriver/firefox/bridge_spec.rb:41:in `block (2 levels) in <module:Firefox>'
```

### CODE REVIEW

**Comment by barancev** [comment]
Merged as d381682663b6f8be6a153542ce7c08a1ad3aabdc
