### ISSUE TITLE
WebElement.location throwing KeyError when python RemoteDriver is used to access FireFox 47.0.1 via marionette

### ISSUE THREAD

**Issue by aaron-p-lehmann** [SeleniumHQ/selenium#2473]
## Meta
OS:  
Windows7

Selenium Version:  
Python 2.53.6

Browser:  
FireFox

Browser Version:  
47.0.1

## Expected Behavior -
WebElement.location property should return the location of the element.

## Actual Behavior -
It throws a KeyError

## Steps to reproduce -
1) Create a RemoteDriver for a Firefox 47.0.1 browser, using Python selenium 2.53.6.
2) Navigate to google.com
3) Find the "Gmail" link `link = driver.find_element_by_link_text("Gmail")`
4) `link.location`

I've chased this into the code, and I believe it's happening in lines 363-372 of selenium/webdriver/remote/webelement.py

In line 367:

`old_loc = self._execute(Command.GET_ELEMENT_RECT)`

old_loc is a reference to a dictionary whose `value` key refers to a dictionary that has a `x` key.
However, on line 370:

`new_loc = {"x": round(old_loc['x']),`

the code tries to access `x` from `old_loc`, rather than `old_loc['value']`.  I think the proper fix is to add a `['value']` to line 367, mirroring the pattern in line 369.

Based on an inspection of the code, it seems similar errors exist in `size` and `rect`.

**Comment by aaron-p-lehmann** [comment]
The value of old_loc is:

```
{
  u'status': 0,
  u'sessionId': u'81900b0c-f61f-4fca-822e-69b3d19bedf2',
  u'value': {
    u'point': None,
    u'dimension': None,
    u'width': 34,
    u'y': 19, u'x': 756,
    u'hCode': 17920133,
    u'height': 24,
    u'class': u'org.openqa.selenium.Rectangle'},
  u'state': u'success',
  u'hCode': 17296148,
  u'class': u'org.openqa.selenium.remote.Response'}
```

**Comment by AutomatedTester** [comment]
I can't reproduce with Marionette

```
Python 2.7.11 (default, Dec 15 2015, 20:53:37)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> f=webdriver.Firefox(capabilities={"marionette": True}
... )
>>> f.get("https://www.google.com")
>>> link = f.find_element_by_link_text("Gmail")
>>> link.location
{'y': 19.0, 'x': 1025.0}
>>> webdriver.__version__
'2.53.6'
>>>
```

**Comment by AutomatedTester** [comment]
>>> f=webdriver.Firefox()
>>> f.get("https://www.google.com")
>>> link = f.find_element_by_link_text("Gmail")
>>> link.location
{'y': 19.0, 'x': 1025.0}
>>> webdriver.__version__
'2.53.6'

**Comment by aaron-p-lehmann** [comment]
From selenium earlier this morning:

> [10:02] CSWookie, "It still happens, I'm using the 2.53 of the standalone server for both the node and the hub.  If I set driver.w3c = False, things work for me, so maybe I can use that as a workaround.  Would it be helpful to you, AutomatedTester, if I put my capabilities directory in a pastebin?"
> [10:02] CSWookie, "I'm using Windows 7 as my node, and centos 6.4 as my hub, if that matters at all."
> [10:08] AutomatedTester, "CSWookie: ahh... that means its a server bug, not sure if davehunt has already fixed this"

**Comment by lukeis** [comment]
closing since that means it's fixed in a future version of firefox :)

If it reproduces against nightly... send a bug to mozilla directly-
https://bugzilla.mozilla.org/buglist.cgi?product=Testing&component=Marionette

**Comment by hsoehalim** [comment]
>>> f=webdriver.Firefox(capabilities={"marionette": True})
>>> f.get("https://www.google.com")
>>> link = f.find_element_by_link_text("Gmail")
>>> link.location
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/selenium-3.3.0-py2.7.egg/selenium/webdriver/remote/webelement.py", line 403, in location
    new_loc = {"x": round(old_loc['x']),
TypeError: 'NoneType' object has no attribute '__getitem__'
>>> webdriver.__version__
'3.3.0'
>>>

**Comment by hsoehalim** [comment]
```
>>> from selenium import webdriver
>>> f=webdriver.Firefox()
>>> f.get("https://www.google.com")
>>> link = f.find_element_by_link_text("Gmail")
>>> link.location
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/selenium-3.3.0-py2.7.egg/selenium/webdriver/remote/webelement.py", line 403, in location
    new_loc = {"x": round(old_loc['x']),
TypeError: 'NoneType' object has no attribute '__getitem__'
>>>
```

**Comment by aarranz** [comment]
I can reproduce it with python 2.7.13, firefox 54.0 and selenium 3.4.3 on mac OS Sierra.

**Comment by aarranz** [comment]
Seems that the problem was related to the use of an old version of geckodriver. I was using: ```
```
$ geckodriver --version
geckodriver 0.11.1
```

The problem disappeared after upgrading it to v0.17.0.
