### ISSUE TITLE
Selenium Maven Plugin

### ISSUE THREAD

**Issue by jcagarcia** [SeleniumHQ/selenium#686]
Hi all,

I'm using *selenium-maven-plugin* 2.3 version with *selenium-server* 2.25.0 version, but I have problems trying to execute selenium tests on new Firefox distributions using _mvn selenium:selenese_

I was reading about this error on https://code.google.com/p/selenium/issues/detail?id=6055 and seems that I need to update my installed selenium  to 2.35 version... 

This is my plugin configuration:

```
<plugin>
   <groupId>org.codehaus.mojo</groupId>
   <artifactId>selenium-maven-plugin</artifactId>
   <version>2.3</version>
   <configuration>
      <browser>*firefox</browser>
      <suite>src/main/webapp/selenium/test-suite.xhtml</suite>
      <results>${project.build.directory}/selenium.html</results>
      <startURL>http://localhost:4444/</startURL>
   </configuration>
   <dependencies>
      <dependency>
         <groupId>org.seleniumhq.selenium</groupId>
         <artifactId>selenium-server</artifactId>
         <version>2.35.0</version>
      </dependency>
   </dependencies>
</plugin>
```

If I update selenium server to this version (2.35.0) or newer (2.46.0), I'm getting an error about API incompatibility with *selenium-maven-plugin*:

```
Failed to execute goal org.codehaus.mojo:selenium-maven-plugin:2.3:selenese (default-cli) on project petclinic: Execution default-cli of goal org.codehaus.mojo:selenium-maven-plugin:2.3:selenese failed: An API incompatibility was encountered while executing org.codehaus.mojo:selenium-maven-plugin:2.3:selenese: java.lang.NoSuchMethodError: org.openqa.selenium.remote.DesiredCapabilities.phantomjs()Lorg/openqa/selenium/remote/DesiredCapabilities;
```

As I've seen, *selenium-maven-plugin* has not been updated since 2012.

http://mvnrepository.com/artifact/org.codehaus.mojo/selenium-maven-plugin/2.3 

so I'm considering to search other selenium maven plugin to execute my tests...

Which selenium maven plugin do you recommend me to use? Do you know some patch or work around to solve this issue on my current *selenium-maven-plugin*?

This issue is related with Spring Roo Project, that generate selenium tests automatically on java applications...

https://jira.spring.io/browse/ROO-3634

We need to know if we can continue using selenium on Spring Roo project or not...

Thanks for your amazing work. We are waiting for your answer.

Best regards,

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by jcagarcia** [comment]
Thank you barancev!

I've moved this issue to Selenium user group.

Best regards,

**Comment by Oleksandr13** [comment]
Selenium maven plugin 2.3 does not work with selenium-server 2.46.0(and higher) version and selenium remote-control 2.0rc2 (FF 45.0.1, Selenium 1.0)

I use

> <plugin>

	<groupId>org.codehaus.mojo</groupId>
	<artifactId>selenium-maven-plugin</artifactId>
	<version>2.3</version>
	<configuration>
		<port>${selenium.port}</port>
		<skip>${selenium.skip}</skip>
		<userExtensions>${project.build.directory}/test-classes/user-extensions.js</userExtensions>				
	</configuration>
	<dependencies>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<version>2.46.0</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-remote-driver</artifactId>
			<version>2.46.0</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-api</artifactId>
			<version>2.46.0</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-remote-control</artifactId>
			<version>2.0rc2</version>
		</dependency>
	</dependencies>
</plugin>

and get 
> java.lang.RuntimeException: Could not start Selenium session: Internal Server Error


It works for FF 41.0.1 and selenium-server 2.45.0


Sorry for comment in this topic.

**Comment by barancev** [comment]
selenium-maven-plugin is not developed by Selenium team, please send bug reports to the plugin developer.

**Comment by paulvi** [comment]
selenium-maven-plugin is not under development

latest version is 2.3 (dated 2012)

See also http://www.mojohaus.org/plugins.html and  
 https://mvnrepository.com/artifact/org.codehaus.mojo/selenium-maven-plugin

I could not find repo or dedicated project page for the selenium-maven-plugin
