### PR TITLE
[py] Remove logging API for non-Chromium browsers 

### LINKED ISSUE #15586: [🐛 Bug]: [py] get_log() doesn't work with WebKitGTK
### Description

Calling the `driver.get_log()` method when using WebKitGTK doesn't work and returns an error.

### Reproducible Code

```shell
from selenium import webdriver

driver = webdriver.WebKitGTK()
print(driver.get_log('browser'))
```

### Debugging Logs

```logs
DEBUG:selenium.webdriver.common.driver_finder:Skipping Selenium Manager; path to MiniBrowser driver specified in Service class: /usr/bin/WebKitWebDriver
DEBUG:selenium.webdriver.common.service:Started executable: `/usr/bin/WebKitWebDriver` in a child process with pid: 14632 using 0 to output -3
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:49185/session {'capabilities': {'firstMatch': [{}], 'alwaysMatch': {'browserName': 'MiniBrowser', 'pageLoadStrategy': <PageLoadStrategy.normal: 'normal'>, 'webkitgtk:browserOptions': {'useOverlayScrollbars': True}}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:49185
DEBUG:urllib3.connectionpool:http://localhost:49185 "POST /session HTTP/1.1" 200 0
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=200 | data={"value":{"sessionId":"db03d1ce-17cd-4f6f-9972-b721c6ae0b2a","capabilities":{"browserName":"MiniBrowser","browserVersion":"2.48","platformName":"linux","acceptInsecureCerts":false,"strictFileInteractability":false,"setWindowRect":true,"unhandledPromptBehavior":"dismiss and notify","pageLoadStrategy":"normal","proxy":{},"timeouts":{"script":30000,"pageLoad":300000,"implicit":0}}}} | headers=HTTPHeaderDict({'Server': 'WebKitWebDriver', 'Date': 'Mon, 07 Apr 2025 17:04:11 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-cache', 'Content-Length': '382'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:49185/session/db03d1ce-17cd-4f6f-9972-b721c6ae0b2a/se/log {'type': 'browser'}
DEBUG:urllib3.connectionpool:http://localhost:49185 "POST /session/db03d1ce-17cd-4f6f-9972-b721c6ae0b2a/se/log HTTP/1.1" 404 0
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=404 | data={"value":{"error":"unknown command","message":"Unknown command: /session/db03d1ce-17cd-4f6f-9972-b721c6ae0b2a/se/log","stacktrace":""}} | headers=HTTPHeaderDict({'Server': 'WebKitWebDriver', 'Date': 'Mon, 07 Apr 2025 17:04:12 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-cache', 'Content-Length': '135'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
Traceback (most recent call last):
  File "/home/cgoldberg617/code/selenium/py/sel.py", line 21, in <module>
    print(driver.get_log('browser'))
          ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/cgoldberg617/code/selenium/py/selenium/webdriver/remote/webdriver.py", line 1192, in get_log
    return self.execute(Command.GET_LOG, {"type": log_type})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cgoldberg617/code/selenium/py/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/cgoldberg617/code/selenium/py/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Unknown command: /session/db03d1ce-17cd-4f6f-9972-b721c6ae0b2a/se/log
```

### LINKED ISSUE #15587: [🐛 Bug]: [py] log_types doesn't work with WebKitGTK
### Description

Accessing the driver.log_types property when using WebKitGTK doesn't work and returns an error.

### Reproducible Code

```shell
from selenium import webdriver

driver = webdriver.WebKitGTK()
print(driver.log_types)
```

### Debugging Logs

```logs
DEBUG:selenium.webdriver.common.driver_finder:Skipping Selenium Manager; path to MiniBrowser driver specified in Service class: /usr/bin/WebKitWebDriver
DEBUG:selenium.webdriver.common.service:Started executable: `/usr/bin/WebKitWebDriver` in a child process with pid: 14725 using 0 to output -3
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:57229/session {'capabilities': {'firstMatch': [{}], 'alwaysMatch': {'browserName': 'MiniBrowser', 'pageLoadStrategy': <PageLoadStrategy.normal: 'normal'>, 'webkitgtk:browserOptions': {'useOverlayScrollbars': True}}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:57229
DEBUG:urllib3.connectionpool:http://localhost:57229 "POST /session HTTP/1.1" 200 0
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=200 | data={"value":{"sessionId":"c978ae59-20c6-409d-9b1e-6ae26fae155e","capabilities":{"browserName":"MiniBrowser","browserVersion":"2.48","platformName":"linux","acceptInsecureCerts":false,"strictFileInteractability":false,"setWindowRect":true,"unhandledPromptBehavior":"dismiss and notify","pageLoadStrategy":"normal","proxy":{},"timeouts":{"script":30000,"pageLoad":300000,"implicit":0}}}} | headers=HTTPHeaderDict({'Server': 'WebKitWebDriver', 'Date': 'Mon, 07 Apr 2025 17:08:49 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-cache', 'Content-Length': '382'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:GET http://localhost:57229/session/c978ae59-20c6-409d-9b1e-6ae26fae155e/se/log/types {}
DEBUG:urllib3.connectionpool:http://localhost:57229 "GET /session/c978ae59-20c6-409d-9b1e-6ae26fae155e/se/log/types HTTP/1.1" 404 0
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=404 | data={"value":{"error":"unknown command","message":"Unknown command: /session/c978ae59-20c6-409d-9b1e-6ae26fae155e/se/log/types","stacktrace":""}} | headers=HTTPHeaderDict({'Server': 'WebKitWebDriver', 'Date': 'Mon, 07 Apr 2025 17:08:50 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-cache', 'Content-Length': '141'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
Traceback (most recent call last):
  File "/home/cgoldberg617/code/selenium/py/sel.py", line 22, in <module>
    print(driver.log_types)
          ^^^^^^^^^^^^^^^^
  File "/home/cgoldberg617/code/selenium/py/selenium/webdriver/remote/webdriver.py", line 1175, in log_types
    return self.execute(Command.GET_AVAILABLE_LOG_TYPES)["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cgoldberg617/code/selenium/py/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/cgoldberg617/code/selenium/py/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Unknown command: /session/c978ae59-20c6-409d-9b1e-6ae26fae155e/se/log/types
```

### LINKED ISSUE #15588: [🐛 Bug]: [py] get_log() doesn't work with Firefox
### Description

Calling the `driver.get_log()` method when using Firefox doesn't work and returns an error.

### Reproducible Code

```shell
from selenium import webdriver

driver = webdriver.Firefox()
print(driver.get_log('browser'))
```

### Debugging Logs

```logs
DEBUG:selenium.webdriver.common.selenium_manager:Selenium Manager binary found at: /home/cgoldberg617/code/selenium/py/selenium/webdriver/common/linux/selenium-manager
DEBUG:selenium.webdriver.common.selenium_manager:Executing process: /home/cgoldberg617/code/selenium/py/selenium/webdriver/common/linux/selenium-manager --browser firefox --debug --language-binding python --output json
DEBUG:selenium.webdriver.common.selenium_manager:geckodriver not found in PATH
DEBUG:selenium.webdriver.common.selenium_manager:firefox not found in PATH
DEBUG:selenium.webdriver.common.selenium_manager:firefox not found in the system
DEBUG:selenium.webdriver.common.selenium_manager:Required browser: firefox 137.0
DEBUG:selenium.webdriver.common.selenium_manager:firefox 137.0 already exists
DEBUG:selenium.webdriver.common.selenium_manager:firefox 137.0 is available at /home/cgoldberg617/.cache/selenium/firefox/linux64/137.0/firefox
DEBUG:selenium.webdriver.common.selenium_manager:Required driver: geckodriver 0.36.0
DEBUG:selenium.webdriver.common.selenium_manager:geckodriver 0.36.0 already in the cache
DEBUG:selenium.webdriver.common.selenium_manager:Driver path: /home/cgoldberg617/.cache/selenium/geckodriver/linux64/0.36.0/geckodriver
DEBUG:selenium.webdriver.common.selenium_manager:Browser path: /home/cgoldberg617/.cache/selenium/firefox/linux64/137.0/firefox
DEBUG:selenium.webdriver.common.service:Started executable: `/home/cgoldberg617/.cache/selenium/geckodriver/linux64/0.36.0/geckodriver` in a child process with pid: 14822 using 0 to output -3
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:60911/session {'capabilities': {'firstMatch': [{}], 'alwaysMatch': {'browserName': 'firefox', 'acceptInsecureCerts': True, 'moz:debuggerAddress': True, 'pageLoadStrategy': <PageLoadStrategy.normal: 'normal'>, 'browserVersion': None, 'moz:firefoxOptions': {'binary': '/home/cgoldberg617/.cache/selenium/firefox/linux64/137.0/firefox', 'prefs': {'remote.active-protocols': 3}}}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:60911
DEBUG:urllib3.connectionpool:http://localhost:60911 "POST /session HTTP/1.1" 200 0
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=200 | data={"value":{"sessionId":"96ed6e1f-9fe9-475e-8d46-5e5726273c6b","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"137.0","moz:accessibilityChecks":false,"moz:buildID":"20250327043313","moz:debuggerAddress":"127.0.0.1:48015","moz:geckodriverVersion":"0.36.0","moz:headless":false,"moz:platformVersion":"6.6.67-06628-g571b599e617d","moz:processID":14825,"moz:profile":"/tmp/rust_mozprofile4fOCFz","moz:shutdownTimeout":60000,"moz:webdriverClick":true,"moz:windowless":false,"pageLoadStrategy":"normal","platformName":"linux","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0"}}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '814', 'date': 'Mon, 07 Apr 2025 17:11:33 GMT'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:60911/session/96ed6e1f-9fe9-475e-8d46-5e5726273c6b/se/log {'type': 'browser'}
DEBUG:urllib3.connectionpool:http://localhost:60911 "POST /session/96ed6e1f-9fe9-475e-8d46-5e5726273c6b/se/log HTTP/1.1" 405 0
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=405 | data=HTTP method not allowed | headers=HTTPHeaderDict({'content-type': 'text/plain; charset=utf-8', 'content-length': '23', 'date': 'Mon, 07 Apr 2025 17:11:37 GMT'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
Traceback (most recent call last):
  File "/home/cgoldberg617/code/selenium/py/sel.py", line 21, in <module>
    print(driver.get_log('browser'))
          ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/cgoldberg617/code/selenium/py/selenium/webdriver/remote/webdriver.py", line 1192, in get_log
    return self.execute(Command.GET_LOG, {"type": log_type})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cgoldberg617/code/selenium/py/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/cgoldberg617/code/selenium/py/selenium/webdriver/remote/errorhandler.py", line 196, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: HTTP method not allowed
```

### LINKED ISSUE #15589: [🐛 Bug]: [py] log_types doesn't work with Firefox
### Description

Accessing the the `driver.log_types` property when using Firefox doesn't work and returns an error.

### Reproducible Code

```shell
from selenium import webdriver

driver = webdriver.Firefox()
print(driver.log_types)
```

### Debugging Logs

```logs
DEBUG:selenium.webdriver.common.selenium_manager:Selenium Manager binary found at: /home/cgoldberg617/code/selenium/py/selenium/webdriver/common/linux/selenium-manager
DEBUG:selenium.webdriver.common.selenium_manager:Executing process: /home/cgoldberg617/code/selenium/py/selenium/webdriver/common/linux/selenium-manager --browser firefox --debug --language-binding python --output json
DEBUG:selenium.webdriver.common.selenium_manager:geckodriver not found in PATH
DEBUG:selenium.webdriver.common.selenium_manager:firefox not found in PATH
DEBUG:selenium.webdriver.common.selenium_manager:firefox not found in the system
DEBUG:selenium.webdriver.common.selenium_manager:Required browser: firefox 137.0
DEBUG:selenium.webdriver.common.selenium_manager:firefox 137.0 already exists
DEBUG:selenium.webdriver.common.selenium_manager:firefox 137.0 is available at /home/cgoldberg617/.cache/selenium/firefox/linux64/137.0/firefox
DEBUG:selenium.webdriver.common.selenium_manager:Required driver: geckodriver 0.36.0
DEBUG:selenium.webdriver.common.selenium_manager:geckodriver 0.36.0 already in the cache
DEBUG:selenium.webdriver.common.selenium_manager:Driver path: /home/cgoldberg617/.cache/selenium/geckodriver/linux64/0.36.0/geckodriver
DEBUG:selenium.webdriver.common.selenium_manager:Browser path: /home/cgoldberg617/.cache/selenium/firefox/linux64/137.0/firefox
DEBUG:selenium.webdriver.common.service:Started executable: `/home/cgoldberg617/.cache/selenium/geckodriver/linux64/0.36.0/geckodriver` in a child process with pid: 15157 using 0 to output -3
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:51515/session {'capabilities': {'firstMatch': [{}], 'alwaysMatch': {'browserName': 'firefox', 'acceptInsecureCerts': True, 'moz:debuggerAddress': True, 'pageLoadStrategy': <PageLoadStrategy.normal: 'normal'>, 'browserVersion': None, 'moz:firefoxOptions': {'binary': '/home/cgoldberg617/.cache/selenium/firefox/linux64/137.0/firefox', 'prefs': {'remote.active-protocols': 3}}}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:51515
DEBUG:urllib3.connectionpool:http://localhost:51515 "POST /session HTTP/1.1" 200 0
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=200 | data={"value":{"sessionId":"d80e7b29-4a89-48d8-9b77-2507968f7220","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"137.0","moz:accessibilityChecks":false,"moz:buildID":"20250327043313","moz:debuggerAddress":"127.0.0.1:60083","moz:geckodriverVersion":"0.36.0","moz:headless":false,"moz:platformVersion":"6.6.67-06628-g571b599e617d","moz:processID":15160,"moz:profile":"/tmp/rust_mozprofileayiDc9","moz:shutdownTimeout":60000,"moz:webdriverClick":true,"moz:windowless":false,"pageLoadStrategy":"normal","platformName":"linux","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0"}}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '814', 'date': 'Mon, 07 Apr 2025 17:14:26 GMT'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:GET http://localhost:51515/session/d80e7b29-4a89-48d8-9b77-2507968f7220/se/log/types {}
DEBUG:urllib3.connectionpool:http://localhost:51515 "GET /session/d80e7b29-4a89-48d8-9b77-2507968f7220/se/log/types HTTP/1.1" 405 0
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=405 | data=HTTP method not allowed | headers=HTTPHeaderDict({'content-type': 'text/plain; charset=utf-8', 'content-length': '23', 'date': 'Mon, 07 Apr 2025 17:14:30 GMT'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
Traceback (most recent call last):
  File "/home/cgoldberg617/code/selenium/py/sel.py", line 22, in <module>
    print(driver.log_types)
          ^^^^^^^^^^^^^^^^
  File "/home/cgoldberg617/code/selenium/py/selenium/webdriver/remote/webdriver.py", line 1175, in log_types
    return self.execute(Command.GET_AVAILABLE_LOG_TYPES)["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cgoldberg617/code/selenium/py/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/cgoldberg617/code/selenium/py/selenium/webdriver/remote/errorhandler.py", line 196, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: HTTP method not allowed
```

### PR DESCRIPTION
**Pull request by cgoldberg**
### 🔗 Related Issues

Fixes #15588 
Fixes #15589
Fixes #15587
Fixes #15586

### 💥 What does this PR do?

This PR changes the logging API in the Python bindings so it only works on Chromium based browsers (Chrome/Edge), as discussed in: https://github.com/SeleniumHQ/selenium/issues/15588

It removes the related methods from the `selenium.webdriver.remote.webdriver.WebDriver` class and adds them to `selenium.webdriver.chromium/webdriver.WebDriver`.

Relevant tests have been updated so the are expected failures on all non-Chromium browsers.

This will bring the Python bindings in line with other language bindings where this has already been removed from most browsers. 

### 🔄 Types of changes
- Breaking change (fix or feature that would cause existing functionality to change)

___

### **PR Type**
Bug fix, Enhancement

### CODE REVIEW

**Comment by titusfortner** [comment]
So I looked deeper at Ruby Selenium code, and we have a MixIn that allows users to call this method from Chromium. So maybe we just want to move this to Chromium driver class and not delete it entirely (sorry for my earlier mixup).

**Comment by cgoldberg** [comment]
OK, I'll update this PR in a little while (and also fix the linting error)

**Comment by cgoldberg** [comment]
It should be all set now... I updated the PR description also.

I moved the logging methods to the Chromium WebDriver class, so it works in Chrome/Edge. I also adjusted the tests to be expected failures on all browsers except Chrome/Edge.

... just waiting for CI to run.

**Comment by cia2154** [comment]
Am I correct in understanding that this PR broke programs that call get_log from webdriver.Remote?
As GraemeWatt mentions, is the only solution to just call driver.execute(Command.GET_LOG, {"type": "<log type>"})["value"]?

The following code works fine in 4.31.0, but doesn't work in 4.32.0.

```
from selenium import webdriver
from selenium.webdriver.remote.command import Command

options = webdriver.ChromeOptions()
options.set_capability('goog:loggingPrefs', {'performance': 'ALL'})

driver = webdriver.Remote(
    command_executor='http://localhost:4444/wd/hub',
    options = options
)

try:
    driver.get('http://example.com')
    # AttributeError: 'WebDriver' object has no attribute 'get_log' in 4.32.0
    print(driver.get_log('performance'))

    # This code works with both versions
    #print(driver.execute(Command.GET_LOG, {"type": "performance"})["value"])

except Exception as e:
    raise e
finally:
    driver.quit()
```

**Comment by cgoldberg** [comment]
@cia2154 yes, that is correct. I will look into restoring it for remote chromedriver/edgedriver.

**Comment by titusfortner** [comment]
@cgoldberg add those methods to here: https://github.com/SeleniumHQ/selenium/blob/9b48eb13829de163ae66c7dc51890bb8b050031c/py/selenium/webdriver/chromium/remote_connection.py#L45

**Comment by cgoldberg** [comment]
@titusfortner I tried to implement this, but I can't find a good way to add `get_log` and `get_log_types` methods to the base `WebDriver` class (for remote) so only Chrome/Edge browsers can access them.

I don't see how adding those methods to `_remote_commands` helps with that.

I think we would need a pretty big restructuring of the class hierarchy to allow Chromium specific methods on a `webdriver.Remote` instance.

Maybe I'm missing something?

**Comment by cgoldberg** [comment]
Thinking about this some more...  The only solution I can think of is to move the `get_log` and `get_log_types` methods back to the parent `WebDriver` class, and also add them to subclasses for non-Chromium browsers... and when they are called from a subclass, just raise `NotImplementedError`.

The methods on the base `WebDriver` class would need to check which browser it's using when  those methods are called and raise `NotImplementedError` if the driver isn't Chrome or Edge.

It's kind of ugly, but this would allow the logging API to be used for Chrome, Edge, and Remote drivers, and give a reasonable error when called from a local or remote driver that is not Chrome or Edge.

**Comment by titusfortner** [comment]
You don't need to throw a not implemented error. There are a bunch of chromium specific features like casting that work with Remote driver.

This isn't a great way to do it to reference subclasses this way, but it avoids mixins which Python people don't like:
https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/remote/webdriver.py#L122 

Literally just add those methods to the list above, and webdriver will add the commands to remote sessions that have that browser name

**Comment by cgoldberg** [comment]
> There are a bunch of chromium specific features like casting that work with Remote driver.

None of the casting methods (like `get_sink`, `start_tab_mirroring`, `stop_casting`) work on Remote webdrivers (because of the same issue I am running into).

> Literally just add those methods to the list above, and webdriver will add the commands to remote sessions that have that browser name

It doesn't. `_remote_commands` is just a mapping of command names to endpoints. For eaxmple, it contains this:

```
"launchApp": ("POST", "/session/$sessionId/chromium/launch_app")
```

There is a method on `chromium.WebDriver` called `launch_app` that references this command. However, you can't call `launch_app` on a Remote instance... it doesn't exist.

So to use any of the commands listed in `_remote_commands`, you have to implement a method that calls the command. Where do I add that method? Do you have an example of a method you can call on a Remote instance that only works for Chromium browsers? I can't find any.

**Comment by AlimTleuliyev** [comment]
Hello! Was this solved? @cgoldberg I am using Remote Driver and I cannot access logs. 

driver.get_log() not avaliable to selenium.webdriver.remote.webdriver

Which version is okay?

**Comment by cgoldberg** [comment]
@AlimTleuliyev it was not. Use the workarounds described in https://github.com/SeleniumHQ/selenium/issues/15772
