### ISSUE TITLE
2.49.0 python driver.quit() error

### ISSUE THREAD

**Issue by rmfitzpatrick** [SeleniumHQ/selenium#1469]
After upgrading to 2.49.0 via pip previously working calls to quit now fail:
```
  File "<trunc>/pyenv/local/lib/python3.4/site-packages/my_lib/uses_driver.py", line 402, in quit_driver
    driver.quit()
  File "<trunc>/pyenv/local/lib/python3.4/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 74, in quit
    self.service.stop()
  File "<trunc>/pyenv/local/lib/python3.4/site-packages/selenium/webdriver/common/service.py", line 124, in stop
    self.process.stdout.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by rmfitzpatrick** [comment]
This use of quit() on a phantomjs webdriver works in 2.48.0

**Comment by kottenator** [comment]
I have the same error with `pytest-selenium`

**Comment by rmfitzpatrick** [comment]
I opened a [PR](https://github.com/SeleniumHQ/selenium/pull/1471) that I believe will fix this.

**Comment by lukeis** [comment]
I agree with the PR... but I'd also like to understand how to reproduce this in the future. With the current code base I do not get the exception on OSX (10.10.5) using py 3.4 (nor 2.7).

Are you starting phantomjs with a custom log file or running on a different OS that causes this?

**Comment by lukeis** [comment]
nevermind... seems i can reproduce it just fine using the released pypi package, but tests weren't failing when run against the code repo.

**Comment by lukeis** [comment]
fixed via cc07382

**Comment by PVN77** [comment]
cool for the fix. Thanks

**Comment by JaniszM** [comment]
For me this error still occurs. Using OSX 10.10.5, on geckodriver 0.11.1 and FireFox 50.0.2. Selenium in python 2.7.
