### ISSUE TITLE
Action.perform -- UnsupportedOperationException

### ISSUE THREAD

**Issue by muratme** [SeleniumHQ/selenium#5131]
When upgrading selenium-java and selenium-server to 3.7.1, we are getting the following error ;

```
        Actions markerAction = new Actions(browser.getWebDriver());
        markerAction.moveToElement(element);
        markerAction.perform();
```

> 
> java.lang.UnsupportedOperationException: Underlying driver does not implement advanced user interactions yet.
> 	at org.openqa.selenium.support.events.EventFiringWebDriver.perform(EventFiringWebDriver.java:345)
> 	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:638)
> 	at org.openqa.selenium.interactions.Actions.perform(Actions.java:594)
> 	at com.sahibinden.selenium.tests.web.search.MapSearchTest.moveToElement(MapSearchTest.java:1067)
> 	at com.sahibinden.selenium.tests.web.search.MapSearchTest.testMarkerTooltipContent(MapSearchTest.java:841)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
> 	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
> 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
> 	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
> 	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
>

**Comment by p0deje** [comment]
Please provide information about browser and driver versions.

**Comment by muratme** [comment]
@p0deje 

Chrome :  Version 62.0.3202.94 (Official Build) (64-bit)
chromedriver : 2.33
OS : High Sierra MACOS

```
<artifactId>selenium-java</artifactId>
<version>3.7.1</version>
```

```
<artifactId>selenium-server</artifactId>
<version>3.7.1</version>

```

**Comment by p0deje** [comment]
How do you instantiate the driver? Please, provide the code that I can run locally reproduce the issue.

**Comment by muratme** [comment]
@p0deje 

```
            case CHROME:
                chromeDriverFocusOnBackground(configuration.getChromedriverBackgroundOption());

                capabilities = null == initialCapabilities ? DesiredCapabilities.chrome() : initialCapabilities;
                capabilities.setCapability("enable-restore-session-state", true);
                capabilities.setJavascriptEnabled(true);
                capabilities.setBrowserName("chrome");
                capabilities.setPlatform(Platform.ANY);

                ChromeOptions options = new ChromeOptions();
                options.addArguments(Arrays.asList("--start-maximized", "allow-running-insecure-content", "ignore-certificate-errors"));

                if (null != customizer)
                {
                    customizer.customizeCapabilities(capabilities);
                    customizer.customizeChromeOptions(options);
                }
                capabilities.setCapability(ChromeOptions.CAPABILITY, options);

                LoggingPreferences logPrefs = new LoggingPreferences();
                logPrefs.enable(LogType.BROWSER, Level.ALL);
                capabilities.setCapability(CapabilityType.LOGGING_PREFS, logPrefs);

                ExecutorService executor = Executors.newSingleThreadExecutor();
                Future<String> future = executor.submit(new Callable<String>()
                {
                    public String call() throws Exception
                    {
                        webDriver = configuration.getRemoteController() ?
                                new RemoteWebDriver(new URL("http://" + SELENIUM_REMOTE_SERVER + ":" + SELENIUM_REMOTE_PORT + "/wd/hub"), capabilities) :
                                new EventFiringWebDriver(new ChromeDriver(capabilities));

                        return "Driver created";
                    }
                });

                try
                {
                    logger.info(future.get(1, TimeUnit.MINUTES)); //timeout is in a seconds
                }
                catch (TimeoutException e)
                {
                    logger.error("WebDriver does not created within 1 Minutes");
                }
                catch (InterruptedException e)
                {
                    e.printStackTrace();
                }
                catch (ExecutionException e)
                {
                    e.printStackTrace();
                }
                executor.shutdownNow();

                webDriver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
                webDriver.manage().timeouts().pageLoadTimeout(90, TimeUnit.SECONDS);
                webDriver.manage().timeouts().setScriptTimeout(90, TimeUnit.SECONDS);
                webDriver.manage().window().maximize();

                break;

```

**Comment by p0deje** [comment]
Trying on current master (3.8.0) I cannot reproduce the problem. Here is the code that I use:

```java
public class AppTest extends TestCase {
    public void testApp() throws InterruptedException {
	ChromeOptions options = new ChromeOptions();
	options.setBinary("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome");
	WebDriver driver = new RemoteWebDriver(options);
	driver.get("http://google.com");

	WebElement element = driver.findElement(By.tagName("button"));
	Actions markerAction = new Actions(driver);
	markerAction.moveToElement(element);
	markerAction.perform();

	driver.quit();
    }
}
```

Can you compose such a simple code that replicates the problem on your side?

**Comment by muratme** [comment]
instead of using RemoteWebDriver in my case ;

> WebDriver driver = new EventFiringWebDriver(new ChromeDriver(capabilities));

```
public class AppTest extends TestCase {
    public void testApp() throws InterruptedException {
	ChromeOptions options = new ChromeOptions();
	options.setBinary("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome");
	WebDriver driver = new EventFiringWebDriver(new ChromeDriver(capabilities));
	driver.get("http://google.com");

	WebElement element = driver.findElement(By.tagName("button"));
	Actions markerAction = new Actions(driver);
	markerAction.moveToElement(element);
	markerAction.perform();

	driver.quit();
    }
}

```

**Comment by p0deje** [comment]
Tried with your changes - it still works just fine.

Can you reproduce the problem using this code?

**Comment by diemol** [comment]
Closing as we didn't get any more information from the OP.
