### ISSUE TITLE
Strange error message after upgrading to 3.0.0

### ISSUE THREAD

**Issue by doberkofler** [SeleniumHQ/selenium#3061]
## Meta -
OS:  
Windows 7
Selenium Version:  
3.0.0
Browser:
Chrome

Browser Version:  
54

## Expected Behavior -
The mocha unit tests worked as expected in 2.53.2

## Actual Behavior -
The test now fails with the following error stack:
```
  1) Selenium Webdriver NodeJS API (selenium_webdriver-test.js) Wait success using a custom promise:
     Error: TypeError: fn is not a function
      at test\selenium\tests\0-helper\selenium_webdriver-test.js:189:10
      at ManagedPromise.invokeCallback_ (node_modules\selenium-webdriver\lib\promise.js:1341:14)
      at TaskQueue.execute_ (node_modules\selenium-webdriver\lib\promise.js:2950:14)
      at TaskQueue.executeNext_ (node_modules\selenium-webdriver\lib\promise.js:2933:27)
      at asyncRun (node_modules\selenium-webdriver\lib\promise.js:2793:27)
      at node_modules\selenium-webdriver\lib\promise.js:675:7
      at process._tickDomainCallback (internal/process/next_tick.js:129:7)
  From: Task: Selenium Webdriver NodeJS API (selenium_webdriver-test.js) Wait success using a custom promise
      at Context.ret (node_modules\selenium-webdriver\testing\index.js:185:10)
      at node_modules\selenium-webdriver\testing\index.js:104:5
      at ManagedPromise.invokeCallback_ (node_modules\selenium-webdriver\lib\promise.js:1341:14)
      at TaskQueue.execute_ (node_modules\selenium-webdriver\lib\promise.js:2950:14)
      at TaskQueue.executeNext_ (node_modules\selenium-webdriver\lib\promise.js:2933:27)
      at asyncRun (node_modules\selenium-webdriver\lib\promise.js:2793:27)
```

## Steps to reproduce -
```
'use strict';

const webdriver = require('selenium-webdriver');

test.describe('Selenium Webdriver NodeJS API (selenium_webdriver-test.js)', function () {
	test.it('Wait success using a custom promise', function () {
		let finished = false;

		function asyncOperation(delay) {
			let deferred = webdriver.promise.defer();
			setTimeout(function () {
				finished = true;
				deferred.fulfill(true);
			}, delay || 100);

			return deferred;
		}

		let deferred = asyncOperation(100);

		let waitPromise = driver.wait(deferred, TIMEOUT, 'waiting for a promise to succeed');

		waitPromise.then(function () {
			assert.strictEqual(finished, true);
		}).catch(function (e) {
			throw new Error(e);
		});
	});
});
```

**Comment by jleyba** [comment]
Your sample doesn't execute as listed. I had to modify it to get it to run, and it works as expected.

```js
'use strict';

const assert = require('assert');
const webdriver = require('selenium-webdriver');
const test = require('selenium-webdriver/testing');

const TIMEOUT = process.env.TIMEOUT ? parseInt(process.env.TIMEOUT, 10) : 30;

test.describe('Selenium Webdriver NodeJS API (selenium_webdriver-test.js)', function () {
	test.it('Wait success using a custom promise', function () {
		let finished = false;

		function asyncOperation(delay) {
			let deferred = webdriver.promise.defer();
			setTimeout(function () {
				finished = true;
				deferred.fulfill(true);
			}, delay || 100);

			return deferred;
		}

		let deferred = asyncOperation(100);

		let waitPromise = webdriver.promise.controlFlow().wait(deferred.promise, TIMEOUT, 'waiting for a promise to succeed');

		waitPromise.then(function () {
			assert.strictEqual(finished, true);
		}).catch(function (e) {
			throw new Error(e);
		});
	});
});
```

```
$ TIMEOUT=30 mocha 3061.js 


  Selenium Webdriver NodeJS API (selenium_webdriver-test.js)
    1) Wait success using a custom promise


  0 passing (17ms)
  1 failing

  1) Selenium Webdriver NodeJS API (selenium_webdriver-test.js) Wait success using a custom promise:
     TypeError: timeout must be a number >= 0: 30
      at scheduleWait (node_modules/selenium-webdriver/lib/promise.js:2036:11)
      at ControlFlow.wait (node_modules/selenium-webdriver/lib/promise.js:2388:12)
      at Context.<anonymous> (3061.js:25:53)
      at runTest (node_modules/selenium-webdriver/testing/index.js:166:22)
      at node_modules/selenium-webdriver/testing/index.js:187:16
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1066:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:186:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2950:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2933:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2840:25)
      at node_modules/selenium-webdriver/lib/promise.js:675:7
  From: Task: Selenium Webdriver NodeJS API (selenium_webdriver-test.js) Wait success using a custom promise
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:185:10)
```

```
$ TIMEOUT=150 mocha 3061.js 


  Selenium Webdriver NodeJS API (selenium_webdriver-test.js)
    ✓ Wait success using a custom promise (111ms)


  1 passing (121ms)
```

**Comment by doberkofler** [comment]
Thank you very much for your support and sorry (as always) for not double checking in the test case is really working after having extracted it from the production code.

I was able to reproduce your working example but am still unable to really understand why my (not complete) test case did work in version 2 but no longer works in version 3:

```javascript
'use strict';

const assert = require('assert');
const webdriver = require('selenium-webdriver');
const test = require('selenium-webdriver/testing');
require('chromedriver');

const TIMEOUT = 200;

test.describe('Selenium Webdriver NodeJS API', function () {
	let driver;

	test.before(function () {
		driver = new webdriver.Builder().forBrowser('chrome').build();
	});

	test.after(function () {
		return driver.quit();
	});

	test.it('Wait success using a custom promise', function () {
		let finished = false;

		function asyncOperation(delay) {
			const deferred = webdriver.promise.defer();
			setTimeout(function () {
				finished = true;
				deferred.fulfill(true);
			}, delay || 100);

			return deferred;
		}

		const deferred = asyncOperation(100);

		const waitPromise = driver.wait(deferred, TIMEOUT, 'waiting for a promise to succeed');
		//const waitPromise = webdriver.promise.controlFlow().wait(deferred.promise, TIMEOUT, 'waiting for a promise to succeed');

		waitPromise.then(function () {
			assert.strictEqual(finished, true);
		}).catch(function (e) {
			throw new Error(e);
		});
	});
});
```

and shows this error message:
```cmd
> node node_modules\mocha\bin\mocha index.js --reporter spec --timeout 10000

  Selenium Webdriver NodeJS API (selenium_webdriver-test.js)
    1) Wait success using a custom promise

  0 passing (1s)
  1 failing

  1) Selenium Webdriver NodeJS API (selenium_webdriver-test.js) Wait success using a custom promise:
     Error: TypeError: fn is not a function
      at index.js:42:10
      at ManagedPromise.invokeCallback_ (node_modules\selenium-webdriver\lib\promise.js:1341:14)
      at TaskQueue.execute_ (node_modules\selenium-webdriver\lib\promise.js:2950:14)
      at TaskQueue.executeNext_ (node_modules\selenium-webdriver\lib\promise.js:2933:27)
      at asyncRun (node_modules\selenium-webdriver\lib\promise.js:2793:27)
      at node_modules\selenium-webdriver\lib\promise.js:675:7
  From: Task: Selenium Webdriver NodeJS API (selenium_webdriver-test.js) Wait success using a custom promise
      at Context.ret (node_modules\selenium-webdriver\testing\index.js:185:10)
```

**Comment by jleyba** [comment]
```js
// Change this:
const waitPromise = driver.wait(deferred, TIMEOUT, 'waiting for a promise to succeed');

// To this (passing deferred.promise):
const waitPromise = driver.wait(deferred.promise, TIMEOUT, 'waiting for a promise to succeed');
```

**Comment by jleyba** [comment]
This was caused by API changes [introduced in 3.0.0-beta-1](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md#v300-beta-1):

> * Removed deprecated functions:
   - Deferred#cancel()
   - Deferred#catch()
   - Deferred#finally()
   - Deferred#isPending()
   - Deferred#then()
   - Promise#thenCatch()
   - Promise#thenFinally()
   - WebDriver#isElementPresent()
   - WebElement#getInnerHtml()
   - WebElement#getOuterHtml()
   - WebElement#getRawId()
   - WebElement#isElementPresent()

**Comment by doberkofler** [comment]
Thank you!
