### ISSUE TITLE
java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal error in selenium-java-2.53.1 

### ISSUE THREAD

**Issue by Aru1** [SeleniumHQ/selenium#2417]
OS:  Windows 7
Selenium Version: 2.53.1
Browser:  Firefox 38.2 

I am using selenium-java-2.53.1 with maven 2.19.1,getting below error:
java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal

It's working fine with selenium-webdriver-2.53.0.

Please provide me solution for this issue.

Thanks in advance.

**Comment by foxrafi** [comment]
The ElementTraversal class belongs to the xml-apis-1.4.01.jar that is new dependency in 2.53.1.
Please try to refresh your Maven dependencies.

**Comment by lukeis** [comment]
it's a transitive dependency of htmlunit, please ask on selenium-users google group if you need help correcting your pom file
