### PR TITLE
[py] use `typing_extensions` to be compatible with `py37`

### LINKED ISSUE #10612: [🐛 Bug]: 4.1.4 Released but only working with Python 3.8+
### What happened?

The new release 4.1.4 is out and is only usable for Python 3.8+
because it relies on version **'Literal' from 'typing'**  which is only available on version 3.8+ of Python.

cannot import name 'Literal' from 'typing' (/usr/local/lib/python3.7/typing.py)

### How can we reproduce the issue?

```shell
Just run a python script using selenium with python < 3.8
```

### Relevant log output

```shell
'Literal' from 'typing'
```

### Operating System

MacOS,Linux

### Selenium version

4.1.4

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chrome

### Are you using Selenium Grid?

_No response_

### PR DESCRIPTION
**Pull request by symonk**
`typing.Literal` is only available in py3.8+; this patch uses `typing-extensions` for older versions.

closes #10612

### CODE REVIEW

**Comment by symonk** [comment]
@diemol CI is running under `python 3.8.10` as mentioned; we need to fix that as soon as poss. and the chrome fails are flaky tests by the looks of it

**Review by AutomatedTester — APPROVED** [review]
