### ISSUE TITLE
[🐛 Bug]: 4.1.4 Released but only working with Python 3.8+

### ISSUE THREAD

**Issue by fofiedelly** [SeleniumHQ/selenium#10612]
### What happened?

The new release 4.1.4 is out and is only usable for Python 3.8+
because it relies on version **'Literal' from 'typing'**  which is only available on version 3.8+ of Python.

cannot import name 'Literal' from 'typing' (/usr/local/lib/python3.7/typing.py)

### How can we reproduce the issue?

```shell
Just run a python script using selenium with python < 3.8
```

### Relevant log output

```shell
'Literal' from 'typing'
```

### Operating System

MacOS,Linux

### Selenium version

4.1.4

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chrome

**Comment by symonk** [comment]
The problem is: 

https://github.com/SeleniumHQ/selenium/blob/d5273d8bc564b4af1cf8eb7688360dc7fab018ab/py/selenium/webdriver/common/virtual_authenticator.py#L22

I will prep a patch now using `typing_extensions`

**Comment by symonk** [comment]
Thanks for the speedy report @fofiedelly; patch up and this has discovered another bug in CI is running against `3.8.10`
