### ISSUE TITLE
WebDriverWait class not present in 3.1.0

### ISSUE THREAD

**Issue by hemanthsridhar** [SeleniumHQ/selenium#3542]
## Meta -
OS:  ANY 
Selenium Version:  3.1.0
Browser:  ANY

java.lang.NoClassDefFoundError: Could not initialize class org.openqa.selenium.support.ui.WebDriverWait

**Comment by ddavison** [comment]
are you including the selenium-support package?

the file [has not been removed](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/support/ui/WebDriverWait.java) from the source tree

**Comment by hemanthsridhar** [comment]
@ddavison I didnt get you

**Comment by hemanthsridhar** [comment]
Needed to add guava library for this to work in 3.1.0. Please add the library so that it because a complete package.
Closing the issue.

**Comment by amyreit** [comment]
I am using 3.3.1 - I've been seeing posts about the deprecation of the old until - I am not sure how to rewrite code that we have that looks like this:

WebDriverWait wait = new WebDriverWait(driver, TIMEOUT * MAX_LOOPS, POLLING);
wait.until(ExpectedConditions.frameToBeAvailableAndSwitchToIt("toolIFrame"));

**Comment by hemanthsridhar** [comment]
@amyreit : did you add the guava library?

**Comment by amyreit** [comment]
I am including the guava 21 library in my class path and it makes Eclipse happy, but we don't use maven, my ant build compile fails 
required: Function<? super WebDriver,T>
found: ExpectedCondition<WebElement>
reason: cannot infer type-variable(s) T

I understand that the old wait is deprecated but when I put in a function I cannot get a compile - even though guava is there, it's not finding the java Function so I'm trying to figure out why it's not seeing my java 8
 
class file for java.util.function.Function not found

**Comment by amyreit** [comment]
I changed this:
 **wait.until(ExpectedConditions.frameToBeAvailableAndSwitchToIt("toolIFrame"));**
 
to this:

        **wait.until(new Function<WebDriver, Boolean>() {
            @Override
            public Boolean apply(WebDriver driver) {
                if (ExpectedConditions.frameToBeAvailableAndSwitchToIt("toolIFrame") == null) {
                    return false;
                } else {
                    return true;
                }
            }
        });**

But when I use Ant to compile, it's giving me the class file for java.util.function.Function not found error  - I have imported com.google.common.base.Function which made Eclipse happy but apparently not ant

**Comment by amyreit** [comment]
I had to add a line to my build xml file to force it to compile with java 8.
  <property name="build.with.java.level" value="1.8" />

**Comment by briansagekeo** [comment]
amy what did you change in your build file to get it to compile?
i have added the ref to guava already and am still seeing issues
