### ISSUE TITLE
[🐛 Bug]: AttributeError: 'service' object has no attribute '_path'

### ISSUE THREAD

**Issue by Hysnijee** [SeleniumHQ/selenium#13678]
### What happened?

I have a python project running natively and Selenium running on a docker container (latest version [selenium/standalone-firefox:4.18.1-20240224]).
When I have configured version 4.8.0 <= the project does connect to the docker container and there are no issues with my crawlers, but for versions 4.9.0 >= they fail with error AttributeError: 'FirefoxRemoteService' object has no attribute '_path'.

These are the configurations:
selenium-firefox:
  driver_executable_path:
  driver_arguments: ['-headless']
   selenium_download_dir: 
  local_download_dir: 
  driver_preferences:

this does work on 4.8.0, but not on 4.9.0.

I did check the changelog but I did not see anything that could help. Trying to update to latest version, but noticed this.

### How can we reproduce the issue?

```shell
selenium-firefox:
  driver_executable_path:
  driver_arguments: ['-headless']
   selenium_download_dir: 
  local_download_dir: 
  driver_preferences:
```

### Relevant log output

```shell
lib\site-packages\selenium\webdriver\common\service.py", line 83, in path
    return self._path
AttributeError: 'FirefoxRemoteService' object has no attribute '_path'
```

### Operating System

Windows 11

### Selenium version

4.18.1

### What are the browser(s) and version(s) where you see this issue?

Firefox 96

### What are the browser driver(s) and version(s) where you see this issue?

Selenium running on docker

**Comment by diemol** [comment]
We are closing this issue as we didn't get a reply from the original poster. 

If someone is facing this issue, feel free to comment and provide a [concise reproducible test case](http://sscce.org/) that includes the page required to execute the scenario (a sample page or a public site).

If you have any questions or need help, join us in the [IRC/Slack channel](https://www.selenium.dev/support/), where the community can also assist you.
