### ISSUE TITLE
Unable to launch chrome browser using selenium 3.1.0

### ISSUE THREAD

**Issue by sanojqa** [SeleniumHQ/selenium#3540]
## Meta -
OS:  
Windows 7
Selenium Version:  
3.1.0
Browser:  
Chrome

I used below code for 3.0.1, it was working:

**System.setProperty("webdriver.chrome.driver", "D:/chromedriver.exe");
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
		driver = new ChromeDriver(capabilities);
		System.out.println(driver);**

The code is not working on selenium version 3.1.0

Error:
===
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V

Have any work around in this version?

**Comment by Vrushabhh** [comment]
Hey,

I think you downloaded Selenium 3.1.0 from NuGet Website. Still **http://www.seleniumhq.org/** not yet announced about this release.

Fix for your issue :- Check your local machine Chrome browser is updated to the latest version. If not then upgrade to latest version.

**Comment by sanojqa** [comment]
@Vrushabhh Now it fixed, I didn't add guava dependency in my pom.xml and working now as expected.

**Comment by manoj9788** [comment]
Fixed to reflect the latest versions via 3f6c050954db8a7b2a638e1a3913865929651a2d

**Comment by didi112113** [comment]
Hi,

I have windows 7 and Chrome  Version is: 57.0.2987.110 (64-bit).  I updated pom.xml with the latest version of Selenium
<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.3.1</version>
I was unable to run the tests.  I also got the error described by Sanojqa and more:

 Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Vat org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32)
  at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:137)
  at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:302)
  at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:88)
  at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:146)

Thank you for your help

**Comment by nirojan0930** [comment]
I have tried the latest version of the guava (22.0) but it's not working for me. I have got the same error again.

**Comment by sanojqa** [comment]
Following are my dependencies in pom.xml and it working for me:

		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>21.0</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.2.0</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<version>3.2.0</version>
		</dependency>

**Comment by saeidlogo** [comment]
if you are using GLASSFIASH as an application sever its about guava conflict with default application server!
set parameter delegate in glassfish-web.xml to false
<class-loader delegate="false"/>

**Comment by nora-white** [comment]
@saeidlogo 's answer solved my problem. 
> if you are using GLASSFIASH as an application sever its about guava conflict with default application server!
> set parameter delegate in glassfish-web.xml to false

I'm building a Java EE application in Netbeans that runs Glassfish. I was trying to run Selenium with ChromeDriver, but continually received the error of "java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V"

By going into my glassfish-web.xml Configuration File, and changing "<class-loader delegate='true'/>" to "<class-loader delegate='false/>", my problem was fixed.

**Comment by mv4263368** [comment]
Hi,

I have windows 7 and Chrome Version is: 75.0.3770.142 (64-bit). I updated pom.xml with the latest version of Selenium

org.seleniumhq.selenium
selenium-java
3.1.4
I was unable to run the tests.
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Vat org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32)
at

**Comment by mv4263368** [comment]
Hi,

I have windows 7 and Chrome Version is: 75.0.3770.142 (64-bit).version of Selenium
org.seleniumhq.selenium
selenium-java
3.1.4
I was unable to run the tests.
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Vat org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32)
at

**Comment by mmerrell** [comment]
The latest version should be "3.141.59".
MM
